// Mocks generated by Mockito 5.4.6 from annotations
// in saas_admin_flutter_app/test/unit/services/brand_service_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i4;

import 'package:dio/dio.dart' as _i5;
import 'package:mockito/mockito.dart' as _i1;
import 'package:saas_admin_flutter_app/core/models/api_response.dart' as _i2;
import 'package:saas_admin_flutter_app/core/services/api_service.dart' as _i3;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class
// ignore_for_file: invalid_use_of_internal_member

class _FakeApiResponse_0<T1> extends _i1.SmartFake
    implements _i2.ApiResponse<T1> {
  _FakeApiResponse_0(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

/// A class which mocks [ApiService].
///
/// See the documentation for Mockito's code generation for more information.
class MockApiService extends _i1.Mock implements _i3.ApiService {
  MockApiService() {
    _i1.throwOnMissingStub(this);
  }

  @override
  void initialize() => super.noSuchMethod(
        Invocation.method(
          #initialize,
          [],
        ),
        returnValueForMissingStub: null,
      );

  @override
  _i4.Future<_i2.ApiResponse<T>> get<T>(
    String? endpoint, {
    Map<String, dynamic>? queryParameters,
    T Function(dynamic)? fromJson,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #get,
          [endpoint],
          {
            #queryParameters: queryParameters,
            #fromJson: fromJson,
          },
        ),
        returnValue: _i4.Future<_i2.ApiResponse<T>>.value(_FakeApiResponse_0<T>(
          this,
          Invocation.method(
            #get,
            [endpoint],
            {
              #queryParameters: queryParameters,
              #fromJson: fromJson,
            },
          ),
        )),
      ) as _i4.Future<_i2.ApiResponse<T>>);

  @override
  _i4.Future<_i2.ApiResponse<T>> post<T>(
    String? endpoint, {
    dynamic data,
    Map<String, dynamic>? queryParameters,
    T Function(dynamic)? fromJson,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #post,
          [endpoint],
          {
            #data: data,
            #queryParameters: queryParameters,
            #fromJson: fromJson,
          },
        ),
        returnValue: _i4.Future<_i2.ApiResponse<T>>.value(_FakeApiResponse_0<T>(
          this,
          Invocation.method(
            #post,
            [endpoint],
            {
              #data: data,
              #queryParameters: queryParameters,
              #fromJson: fromJson,
            },
          ),
        )),
      ) as _i4.Future<_i2.ApiResponse<T>>);

  @override
  _i4.Future<_i2.ApiResponse<T>> put<T>(
    String? endpoint, {
    dynamic data,
    Map<String, dynamic>? queryParameters,
    T Function(dynamic)? fromJson,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #put,
          [endpoint],
          {
            #data: data,
            #queryParameters: queryParameters,
            #fromJson: fromJson,
          },
        ),
        returnValue: _i4.Future<_i2.ApiResponse<T>>.value(_FakeApiResponse_0<T>(
          this,
          Invocation.method(
            #put,
            [endpoint],
            {
              #data: data,
              #queryParameters: queryParameters,
              #fromJson: fromJson,
            },
          ),
        )),
      ) as _i4.Future<_i2.ApiResponse<T>>);

  @override
  _i4.Future<_i2.ApiResponse<T>> delete<T>(
    String? endpoint, {
    Map<String, dynamic>? queryParameters,
    T Function(dynamic)? fromJson,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #delete,
          [endpoint],
          {
            #queryParameters: queryParameters,
            #fromJson: fromJson,
          },
        ),
        returnValue: _i4.Future<_i2.ApiResponse<T>>.value(_FakeApiResponse_0<T>(
          this,
          Invocation.method(
            #delete,
            [endpoint],
            {
              #queryParameters: queryParameters,
              #fromJson: fromJson,
            },
          ),
        )),
      ) as _i4.Future<_i2.ApiResponse<T>>);

  @override
  _i4.Future<_i2.ApiResponse<T>> uploadFile<T>(
    String? endpoint,
    String? filePath, {
    String? fieldName = 'file',
    Map<String, dynamic>? additionalData,
    T Function(dynamic)? fromJson,
    _i5.ProgressCallback? onSendProgress,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #uploadFile,
          [
            endpoint,
            filePath,
          ],
          {
            #fieldName: fieldName,
            #additionalData: additionalData,
            #fromJson: fromJson,
            #onSendProgress: onSendProgress,
          },
        ),
        returnValue: _i4.Future<_i2.ApiResponse<T>>.value(_FakeApiResponse_0<T>(
          this,
          Invocation.method(
            #uploadFile,
            [
              endpoint,
              filePath,
            ],
            {
              #fieldName: fieldName,
              #additionalData: additionalData,
              #fromJson: fromJson,
              #onSendProgress: onSendProgress,
            },
          ),
        )),
      ) as _i4.Future<_i2.ApiResponse<T>>);

  @override
  _i4.Future<_i2.ApiResponse<String>> downloadFile(
    String? endpoint,
    String? savePath, {
    _i5.ProgressCallback? onReceiveProgress,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #downloadFile,
          [
            endpoint,
            savePath,
          ],
          {#onReceiveProgress: onReceiveProgress},
        ),
        returnValue: _i4.Future<_i2.ApiResponse<String>>.value(
            _FakeApiResponse_0<String>(
          this,
          Invocation.method(
            #downloadFile,
            [
              endpoint,
              savePath,
            ],
            {#onReceiveProgress: onReceiveProgress},
          ),
        )),
      ) as _i4.Future<_i2.ApiResponse<String>>);

  @override
  void cancelRequests() => super.noSuchMethod(
        Invocation.method(
          #cancelRequests,
          [],
        ),
        returnValueForMissingStub: null,
      );
}
