package routes

import (
	"log"

	"github.com/gin-gonic/gin"
	"gorm.io/gorm"

	"github.com/liquorpro/go-backend/internal/excise/handlers"
	"github.com/liquorpro/go-backend/internal/excise/services"
	"github.com/liquorpro/go-backend/pkg/shared/cache"
	"github.com/liquorpro/go-backend/pkg/shared/config"
	"github.com/liquorpro/go-backend/pkg/shared/middleware"
)

// SetupExciseRoutes sets up all excise-related routes with authentication
func SetupExciseRoutes(router *gin.Engine, db *gorm.DB, jwtConfig config.JWTConfig, cacheClient *cache.Cache) {
	// Initialize services
	licenseService := services.NewLicenseService(db)

	// Initialize portal client (use mock for development)
	// For production, use: services.NewPortalClient(baseURL, apiKey)
	mockPortalClient := services.NewMockPortalClient(false)
	// Convert mock to PortalClient interface by creating a real one (using mock settings)
	portalClient := services.NewPortalClient("http://localhost:9000", "mock-api-key")
	_ = mockPortalClient // Keep for reference

	reportService := services.NewDailyReportService(db, portalClient)
	securityService := services.NewSecurityCodeService(db)
	complianceService := services.NewComplianceService(db, licenseService)

	// Initialize handlers
	exciseHandlers := handlers.NewExciseHandlers(
		licenseService,
		reportService,
		securityService,
		complianceService,
	)

	// Create excise API group with authentication
	excise := router.Group("/api/excise")

	// Health check endpoint (public - no auth required)
	excise.GET("/health", func(c *gin.Context) {
		c.JSON(200, gin.H{
			"status":  "healthy",
			"service": "excise",
			"version": "1.0.0",
		})
	})

	// Apply authentication middleware to all other routes
	excise.Use(middleware.AuthMiddleware(jwtConfig, cacheClient))
	excise.Use(middleware.TenantMiddleware())

	// ===================== LICENSE ROUTES =====================
	licenses := excise.Group("/licenses")
	{
		licenses.GET("", exciseHandlers.GetLicenses)                                // List all licenses
		licenses.POST("", exciseHandlers.CreateLicense)                             // Create license
		licenses.GET("/:id", exciseHandlers.GetLicenseByID)                         // Get license by ID
		licenses.PUT("/:id", exciseHandlers.UpdateLicense)                          // Update license
		licenses.POST("/:id/renew", exciseHandlers.RenewLicense)                    // Renew license
		licenses.POST("/pay-fee", exciseHandlers.PayLicenseFee)                     // Pay license fee
		licenses.GET("/:id/fee-payments", exciseHandlers.GetLicenseFeePayments)     // Get fee payment history
		licenses.GET("/:id/compliance-status", exciseHandlers.GetLicenseComplianceStatus) // Get compliance status
	}

	// ===================== DAILY REPORT ROUTES =====================
	reports := excise.Group("/daily-reports")
	{
		reports.GET("", exciseHandlers.GetDailyReports)                             // List daily reports
		reports.POST("/auto-generate", exciseHandlers.AutoGenerateDailyReport)      // Auto-generate report
		reports.GET("/date/:date", exciseHandlers.GetDailyReportByDate)             // Get report by date
		reports.GET("/:id", exciseHandlers.GetDailyReportByID)                      // Get report by ID
		reports.POST("/:id/upload-to-portal", exciseHandlers.UploadReportToPortal)  // Upload to portal
		reports.POST("/:id/retry-upload", exciseHandlers.RetryReportUpload)         // Retry failed upload
	}

	// ===================== SECURITY CODE ROUTES =====================
	securityCodes := excise.Group("/security-codes")
	{
		securityCodes.POST("/validate", exciseHandlers.ValidateSecurityCode)        // Validate security code
		securityCodes.POST("/bulk-add", exciseHandlers.BulkAddSecurityCodes)        // Bulk add codes
		securityCodes.GET("/:code", exciseHandlers.GetSecurityCode)                 // Get security code
		securityCodes.GET("/search", exciseHandlers.SearchSecurityCodes)            // Search codes
		securityCodes.POST("/mark-sold", exciseHandlers.MarkSecurityCodesAsSold)    // Mark as sold
		securityCodes.POST("/mark-damaged", exciseHandlers.MarkSecurityCodesAsDamaged) // Mark as damaged
		securityCodes.GET("/stats", exciseHandlers.GetSecurityCodeStats)            // Get statistics
	}

	// ===================== COMPLIANCE ROUTES =====================
	compliance := excise.Group("/compliance")
	{
		compliance.GET("/dashboard", exciseHandlers.GetComplianceDashboard)         // Compliance dashboard
		compliance.GET("/logs", exciseHandlers.GetComplianceLogs)                   // Compliance logs
		compliance.GET("/expiring-licenses", exciseHandlers.GetExpiringLicenses)    // Expiring licenses
		compliance.GET("/pending-fees", exciseHandlers.GetPendingLicenseFees)       // Pending fees
		compliance.GET("/consideration-fees", exciseHandlers.GetConsiderationFeeSummary) // Consideration fee summary
		compliance.GET("/report", exciseHandlers.GetComplianceReport)               // Comprehensive report
	}

	log.Println("Excise routes registered successfully with authentication enabled")
}
