# Copy this file to .github/workflows/flutter-ci-cd.yml
name: Flutter CI/CD Pipeline

on:
  push:
    branches: [ main, develop ]
    paths: ['Flutter_App/**']
  pull_request:
    branches: [ main, develop ]
    paths: ['Flutter_App/**']

env:
  FLUTTER_VERSION: '3.24.3'
  WORKING_DIRECTORY: './Flutter_App'

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - uses: subosito/flutter-action@v2
      with:
        flutter-version: ${{ env.FLUTTER_VERSION }}
    - name: Get dependencies
      working-directory: ${{ env.WORKING_DIRECTORY }}
      run: flutter pub get
    - name: Analyze code
      working-directory: ${{ env.WORKING_DIRECTORY }}
      run: flutter analyze
    - name: Run tests
      working-directory: ${{ env.WORKING_DIRECTORY }}
      run: flutter test --coverage
    - name: Run UX validation
      working-directory: ${{ env.WORKING_DIRECTORY }}
      run: python3 industrial_ux_validator.py

  build:
    needs: test
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - uses: subosito/flutter-action@v2
      with:
        flutter-version: ${{ env.FLUTTER_VERSION }}
    - uses: actions/setup-java@v4
      with:
        distribution: 'zulu'
        java-version: '17'
    - name: Get dependencies
      working-directory: ${{ env.WORKING_DIRECTORY }}
      run: flutter pub get
    - name: Build APK
      working-directory: ${{ env.WORKING_DIRECTORY }}
      run: flutter build apk --release