name: liquorpro_mobile
description: "LiquorPro - Premium Liquor Store Management Mobile Application"
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.1.0 <4.0.0'
  flutter: ">=3.13.0"

dependencies:
  flutter:
    sdk: flutter
  
  # Core Architecture & State Management
  flutter_riverpod: ^2.4.9
  riverpod_annotation: ^2.3.3
  go_router: ^12.1.1
  auto_route: ^7.9.2
  
  # HTTP & API
  dio: ^5.4.0
  retrofit: ^4.0.3
  json_annotation: ^4.8.1
  
  # Local Storage & Security
  flutter_secure_storage: ^9.0.0
  shared_preferences: ^2.2.2
  hive_flutter: ^1.1.0
  drift: ^2.14.1
  
  # UI & Animations
  flutter_animate: ^4.3.0
  lottie: ^2.7.0
  flutter_svg: ^2.0.9
  shimmer: ^3.0.0
  flutter_staggered_animations: ^1.1.1
  smooth_page_indicator: ^1.1.0
  
  # Image & Media
  cached_network_image: ^3.3.0
  image_picker: ^1.0.4
  flutter_image_compress: ^2.1.0
  photo_view: ^0.14.0
  
  # Authentication & Biometrics
  local_auth: ^2.1.7
  google_sign_in: ^6.2.1
  sign_in_with_apple: ^5.0.0
  crypto: ^3.0.3
  
  # Utilities
  intl: ^0.19.0
  uuid: ^4.2.1
  path_provider: ^2.1.1
  url_launcher: ^6.2.2
  share_plus: ^7.2.1
  
  # Networking & Connectivity
  connectivity_plus: ^5.0.2
  internet_connection_checker: ^1.0.0+1
  
  # Device Features
  mobile_scanner: ^3.5.2
  permission_handler: ^11.1.0
  device_info_plus: ^9.1.1
  package_info_plus: ^4.2.0
  
  # Notifications
  firebase_messaging: ^14.7.10
  flutter_local_notifications: ^16.3.0
  awesome_notifications: ^0.8.2
  
  # Performance & Monitoring
  firebase_analytics: ^10.7.4
  firebase_crashlytics: ^3.4.8
  firebase_performance: ^0.9.3+16
  sentry_flutter: ^7.13.2
  
  # Charts & Data Visualization
  fl_chart: ^0.65.0
  syncfusion_flutter_charts: ^23.2.7
  
  # Form & Validation
  reactive_forms: ^16.1.1
  form_builder_validators: ^9.1.0
  
  # Loading & Progress
  flutter_spinkit: ^5.2.0
  percent_indicator: ^4.2.3
  
  # Testing & Development
  logger: ^2.0.2+1
  pretty_dio_logger: ^1.3.1
  
  # Platform Integration
  native_splash: ^2.3.7
  flutter_launcher_icons: ^0.13.1
  
  # Additional Premium Features
  vibration: ^1.8.4
  haptic_feedback: ^0.5.0+1
  qr_code_scanner: ^1.0.1
  flutter_keyboard_visibility: ^6.0.0
  
  # Cupertino Icons (iOS Style)
  cupertino_icons: ^1.0.6

dev_dependencies:
  flutter_test:
    sdk: flutter
  
  # Code Generation & Build
  build_runner: ^2.4.7
  riverpod_generator: ^2.3.9
  auto_route_generator: ^7.3.2
  retrofit_generator: ^8.0.4
  json_serializable: ^6.7.1
  drift_dev: ^2.14.1
  
  # Code Quality & Analysis
  flutter_lints: ^3.0.1
  very_good_analysis: ^5.1.0
  custom_lint: ^0.5.7
  riverpod_lint: ^2.3.7
  
  # Testing
  mocktail: ^1.0.2
  integration_test:
    sdk: flutter
  patrol: ^2.6.0
  
  # Assets & Icons
  flutter_launcher_icons: ^0.13.1
  flutter_native_splash: ^2.3.7

# Flutter Configuration
flutter:
  uses-material-design: true
  generate: true
  
  # Assets
  assets:
    - assets/images/
    - assets/icons/
    - assets/lottie/
    - assets/fonts/
    - assets/sounds/
    - assets/config/
  
  # Custom Fonts
  fonts:
    - family: Inter
      fonts:
        - asset: assets/fonts/Inter-Regular.ttf
          weight: 400
        - asset: assets/fonts/Inter-Medium.ttf
          weight: 500
        - asset: assets/fonts/Inter-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/Inter-Bold.ttf
          weight: 700
        - asset: assets/fonts/Inter-ExtraBold.ttf
          weight: 800
    
    - family: Poppins
      fonts:
        - asset: assets/fonts/Poppins-Regular.ttf
          weight: 400
        - asset: assets/fonts/Poppins-Medium.ttf
          weight: 500
        - asset: assets/fonts/Poppins-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/Poppins-Bold.ttf
          weight: 700

# Native Splash Configuration
flutter_native_splash:
  color: "#0A0A0A"
  image: assets/images/splash_logo.png
  branding: assets/images/splash_branding.png
  color_dark: "#000000"
  image_dark: assets/images/splash_logo_dark.png
  android_12:
    image: assets/images/splash_logo_android12.png
    icon_background_color: "#0A0A0A"
    image_dark: assets/images/splash_logo_android12_dark.png
    icon_background_color_dark: "#000000"

# App Icons Configuration  
flutter_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/images/app_icon.png"
  min_sdk_android: 21
  adaptive_icon_background: "#0A0A0A"
  adaptive_icon_foreground: "assets/images/app_icon_foreground.png"