package services

import (
	"errors"
	"fmt"
	"strings"
	"time"

	"github.com/google/uuid"
	"gorm.io/gorm"

	"github.com/liquorpro/go-backend/internal/excise/models"
	sharedModels "github.com/liquorpro/go-backend/pkg/shared/models"
)

type DailyReportService struct {
	db            *gorm.DB
	portalClient  *PortalClient
}

func NewDailyReportService(db *gorm.DB, portalClient *PortalClient) *DailyReportService {
	return &DailyReportService{
		db:           db,
		portalClient: portalClient,
	}
}

// AutoGenerateDailyReport automatically generates a daily report from sales, purchases, and collections
func (s *DailyReportService) AutoGenerateDailyReport(tenantID uuid.UUID, req models.AutoGenerateReportRequest) (*models.ExciseDailyReport, error) {
	// Validate shop and license
	var shop sharedModels.Shop
	if err := s.db.Where("id = ? AND tenant_id = ?", req.ShopID, tenantID).First(&shop).Error; err != nil {
		return nil, fmt.Errorf("shop not found: %w", err)
	}

	var license models.ExciseLicense
	if err := s.db.Where("shop_id = ? AND is_active = ?", req.ShopID, true).First(&license).Error; err != nil {
		return nil, fmt.Errorf("no active license found for shop: %w", err)
	}

	// Check if report already exists for this date
	var existingReport models.ExciseDailyReport
	if err := s.db.Where("shop_id = ? AND report_date = ?", req.ShopID, req.ReportDate).First(&existingReport).Error; err == nil {
		return nil, errors.New("report already exists for this date")
	}

	reportDate := req.ReportDate.Truncate(24 * time.Hour)

	// 1. Get opening stock (yesterday's closing stock)
	openingStock, err := s.getOpeningStock(req.ShopID, reportDate)
	if err != nil {
		return nil, fmt.Errorf("failed to get opening stock: %w", err)
	}

	// 2. Get stock lifted today (purchases)
	stockLifted, err := s.getStockLifted(req.ShopID, reportDate, tenantID)
	if err != nil {
		return nil, fmt.Errorf("failed to get stock lifted: %w", err)
	}

	// 3. Get sales today
	sales, err := s.getSales(req.ShopID, reportDate, tenantID)
	if err != nil {
		return nil, fmt.Errorf("failed to get sales: %w", err)
	}

	// 4. Get returns today
	returns, err := s.getReturns(req.ShopID, reportDate, tenantID)
	if err != nil {
		return nil, fmt.Errorf("failed to get returns: %w", err)
	}

	// 5. Calculate closing stock
	closingStock := s.calculateClosingStock(openingStock, stockLifted, sales, returns)

	// 6. Get money collection for today
	var moneyCollection sharedModels.MoneyCollection
	moneyCollectionID := (*uuid.UUID)(nil)
	if err := s.db.Where("shop_id = ? AND DATE(collection_date) = ?", req.ShopID, reportDate.Format("2006-01-02")).
		First(&moneyCollection).Error; err == nil {
		moneyCollectionID = &moneyCollection.ID
	}

	// 7. Get cash deposit for today
	var cashDeposit sharedModels.CashDeposit
	cashDepositID := (*uuid.UUID)(nil)
	if err := s.db.Where("shop_id = ? AND DATE(deposit_date) = ?", req.ShopID, reportDate.Format("2006-01-02")).
		First(&cashDeposit).Error; err == nil {
		cashDepositID = &cashDeposit.ID
	}

	// 8. Sum consideration fees paid today
	considerationFeePaid := s.getConsiderationFeesPaid(tenantID, reportDate)

	// Create daily report (TenantModel provides ID and TenantID automatically)
	report := &models.ExciseDailyReport{
		ShopID:                req.ShopID,
		LicenseID:             license.ID,
		ReportDate:            reportDate,
		OpeningStock:          openingStock,
		StockLifted:           stockLifted,
		Sales:                 sales,
		Returns:               returns,
		ClosingStock:          closingStock,
		MoneyCollectionID:     moneyCollectionID,
		CashDepositID:         cashDepositID,
		ConsiderationFeePaid:  considerationFeePaid,
		UploadedToPortal:      false,
		UploadAttempts:        0,
		GeneratedAutomatically: true,
	}
	// Set TenantID manually since we have it
	report.TenantID = &tenantID

	// Save report
	if err := s.db.Create(report).Error; err != nil {
		return nil, fmt.Errorf("failed to create report: %w", err)
	}

	// Update money collection and cash deposit with report link
	if moneyCollectionID != nil {
		s.db.Model(&moneyCollection).Updates(map[string]interface{}{
			"excise_report_id":            report.ID,
			"included_in_excise_report":   true,
		})
	}
	if cashDepositID != nil {
		s.db.Model(&cashDeposit).Updates(map[string]interface{}{
			"excise_report_id":      report.ID,
			"is_daily_sales_deposit": true,
			"sales_date":             reportDate,
		})
	}

	// Log compliance event
	s.logComplianceEvent(tenantID, "daily_report_generated", "info",
		fmt.Sprintf("Daily report generated for %s", reportDate.Format("2006-01-02")),
		map[string]interface{}{
			"report_id":   report.ID,
			"shop_id":     req.ShopID,
			"report_date": reportDate,
		})

	return report, nil
}

// getOpeningStock retrieves yesterday's closing stock
func (s *DailyReportService) getOpeningStock(shopID uuid.UUID, reportDate time.Time) (models.StockBreakdown, error) {
	yesterday := reportDate.AddDate(0, 0, -1)

	var yesterdayReport models.ExciseDailyReport
	if err := s.db.Where("shop_id = ? AND report_date = ?", shopID, yesterday).First(&yesterdayReport).Error; err != nil {
		// No previous report, return empty stock
		return models.StockBreakdown{
			CountryLiquor: []models.BottleEntry{},
			IMFL:          []models.BottleEntry{},
			Beer:          []models.BottleEntry{},
			Wine:          []models.BottleEntry{},
			TotalBottles:  0,
			TotalValue:    0,
		}, nil
	}

	return yesterdayReport.ClosingStock, nil
}

// getStockLifted retrieves today's purchases (stock lifted from godowns)
func (s *DailyReportService) getStockLifted(shopID uuid.UUID, reportDate time.Time, tenantID uuid.UUID) (models.StockBreakdown, error) {
	var purchases []sharedModels.StockPurchase
	if err := s.db.Where("shop_id = ? AND tenant_id = ? AND DATE(purchase_date) = ?",
		shopID, tenantID, reportDate.Format("2006-01-02")).
		Preload("Items").
		Find(&purchases).Error; err != nil {
		return models.StockBreakdown{}, fmt.Errorf("failed to fetch purchases: %w", err)
	}

	return s.buildStockBreakdownFromPurchases(purchases), nil
}

// getSales retrieves today's sales
func (s *DailyReportService) getSales(shopID uuid.UUID, reportDate time.Time, tenantID uuid.UUID) (models.StockBreakdown, error) {
	var sales []sharedModels.Sale
	if err := s.db.Where("shop_id = ? AND tenant_id = ? AND DATE(sale_date) = ?",
		shopID, tenantID, reportDate.Format("2006-01-02")).
		Preload("Items").
		Find(&sales).Error; err != nil {
		return models.StockBreakdown{}, fmt.Errorf("failed to fetch sales: %w", err)
	}

	return s.buildStockBreakdownFromSales(sales), nil
}

// getReturns retrieves today's returns
func (s *DailyReportService) getReturns(shopID uuid.UUID, reportDate time.Time, tenantID uuid.UUID) (models.StockBreakdown, error) {
	var returns []sharedModels.SaleReturn
	if err := s.db.Where("shop_id = ? AND tenant_id = ? AND DATE(return_date) = ?",
		shopID, tenantID, reportDate.Format("2006-01-02")).
		Preload("Items").
		Find(&returns).Error; err != nil {
		return models.StockBreakdown{}, fmt.Errorf("failed to fetch returns: %w", err)
	}

	return s.buildStockBreakdownFromReturns(returns), nil
}

// calculateClosingStock calculates closing stock
func (s *DailyReportService) calculateClosingStock(opening, lifted, sales, returns models.StockBreakdown) models.StockBreakdown {
	closing := models.StockBreakdown{
		CountryLiquor: []models.BottleEntry{},
		IMFL:          []models.BottleEntry{},
		Beer:          []models.BottleEntry{},
		Wine:          []models.BottleEntry{},
	}

	// Opening + Lifted + Returns - Sales = Closing
	// Group by product and sum quantities
	productMap := make(map[string]*models.BottleEntry)

	// Add opening stock
	s.addToProductMap(productMap, opening)
	// Add lifted stock
	s.addToProductMap(productMap, lifted)
	// Add returns
	s.addToProductMap(productMap, returns)
	// Subtract sales
	s.subtractFromProductMap(productMap, sales)

	// Categorize by excise category
	for _, entry := range productMap {
		if entry.Quantity <= 0 {
			continue
		}

		// Get product to determine category
		var product sharedModels.Product
		if err := s.db.Preload("Category").First(&product, "id = ?", entry.ProductID).Error; err == nil {
			// Use category name to determine bottle type
			categoryName := ""
			if product.Category != nil {
				categoryName = product.Category.Name
			}

			switch {
			case contains(categoryName, "Country") || contains(categoryName, "CL"):
				closing.CountryLiquor = append(closing.CountryLiquor, *entry)
			case contains(categoryName, "IMFL") || contains(categoryName, "Whisky") || contains(categoryName, "Vodka") || contains(categoryName, "Rum"):
				closing.IMFL = append(closing.IMFL, *entry)
			case contains(categoryName, "Beer"):
				closing.Beer = append(closing.Beer, *entry)
			case contains(categoryName, "Wine"):
				closing.Wine = append(closing.Wine, *entry)
			default:
				// Default to IMFL if not specified
				closing.IMFL = append(closing.IMFL, *entry)
			}
		}
	}

	// Calculate totals
	closing.CalculateTotals()

	return closing
}

// Helper functions for stock calculation
func (s *DailyReportService) addToProductMap(productMap map[string]*models.BottleEntry, breakdown models.StockBreakdown) {
	allEntries := append(breakdown.CountryLiquor, breakdown.IMFL...)
	allEntries = append(allEntries, breakdown.Beer...)
	allEntries = append(allEntries, breakdown.Wine...)

	for _, entry := range allEntries {
		if existing, ok := productMap[entry.ProductID]; ok {
			existing.Quantity += entry.Quantity
			existing.SecurityCodes = append(existing.SecurityCodes, entry.SecurityCodes...)
		} else {
			newEntry := entry
			productMap[entry.ProductID] = &newEntry
		}
	}
}

func (s *DailyReportService) subtractFromProductMap(productMap map[string]*models.BottleEntry, breakdown models.StockBreakdown) {
	allEntries := append(breakdown.CountryLiquor, breakdown.IMFL...)
	allEntries = append(allEntries, breakdown.Beer...)
	allEntries = append(allEntries, breakdown.Wine...)

	for _, entry := range allEntries {
		if existing, ok := productMap[entry.ProductID]; ok {
			existing.Quantity -= entry.Quantity
		}
	}
}

// buildStockBreakdownFromPurchases builds stock breakdown from purchases
func (s *DailyReportService) buildStockBreakdownFromPurchases(purchases []sharedModels.StockPurchase) models.StockBreakdown {
	breakdown := models.StockBreakdown{
		CountryLiquor: []models.BottleEntry{},
		IMFL:          []models.BottleEntry{},
		Beer:          []models.BottleEntry{},
		Wine:          []models.BottleEntry{},
	}

	for _, purchase := range purchases {
		for _, item := range purchase.Items {
			var product sharedModels.Product
			if err := s.db.Preload("Category").First(&product, "id = ?", item.ProductID).Error; err != nil {
				continue
			}

			// Get security codes for this product from bottle_security_codes table
			var securityCodes []string
			var codes []models.BottleSecurityCode
			s.db.Where("stock_purchase_id = ? AND product_id = ?", purchase.ID, item.ProductID).
				Find(&codes)
			for _, code := range codes {
				securityCodes = append(securityCodes, code.SecurityCode)
			}

			entry := models.BottleEntry{
				ProductID:     item.ProductID.String(),
				ProductName:   product.Name,
				Quantity:      item.Quantity,
				UnitPrice:     item.UnitCost, // Use UnitCost from StockPurchaseItem
				TotalValue:    item.TotalCost,
				SecurityCodes: securityCodes,
			}

			// Use category name to determine bottle type
			categoryName := ""
			if product.Category != nil {
				categoryName = product.Category.Name
			}

			switch {
			case contains(categoryName, "Country") || contains(categoryName, "CL"):
				breakdown.CountryLiquor = append(breakdown.CountryLiquor, entry)
			case contains(categoryName, "IMFL") || contains(categoryName, "Whisky") || contains(categoryName, "Vodka") || contains(categoryName, "Rum"):
				breakdown.IMFL = append(breakdown.IMFL, entry)
			case contains(categoryName, "Beer"):
				breakdown.Beer = append(breakdown.Beer, entry)
			case contains(categoryName, "Wine"):
				breakdown.Wine = append(breakdown.Wine, entry)
			default:
				breakdown.IMFL = append(breakdown.IMFL, entry)
			}
		}
	}

	breakdown.CalculateTotals()
	return breakdown
}

// buildStockBreakdownFromSales builds stock breakdown from sales
func (s *DailyReportService) buildStockBreakdownFromSales(sales []sharedModels.Sale) models.StockBreakdown {
	breakdown := models.StockBreakdown{
		CountryLiquor: []models.BottleEntry{},
		IMFL:          []models.BottleEntry{},
		Beer:          []models.BottleEntry{},
		Wine:          []models.BottleEntry{},
	}

	for _, sale := range sales {
		for _, item := range sale.Items {
			var product sharedModels.Product
			if err := s.db.Preload("Category").First(&product, "id = ?", item.ProductID).Error; err != nil {
				continue
			}

			// Get security codes for this sale
			var securityCodes []string
			var codes []models.BottleSecurityCode
			s.db.Where("sale_id = ? AND product_id = ?", sale.ID, item.ProductID).
				Find(&codes)
			for _, code := range codes {
				securityCodes = append(securityCodes, code.SecurityCode)
			}

			// Calculate total = quantity * unitPrice - discountAmount
			totalValue := (float64(item.Quantity) * item.UnitPrice) - item.DiscountAmount

			entry := models.BottleEntry{
				ProductID:     item.ProductID.String(),
				ProductName:   product.Name,
				Quantity:      item.Quantity,
				UnitPrice:     item.UnitPrice,
				TotalValue:    totalValue,
				SecurityCodes: securityCodes,
			}

			// Use category name to determine bottle type
			categoryName := ""
			if product.Category != nil {
				categoryName = product.Category.Name
			}

			switch {
			case contains(categoryName, "Country") || contains(categoryName, "CL"):
				breakdown.CountryLiquor = append(breakdown.CountryLiquor, entry)
			case contains(categoryName, "IMFL") || contains(categoryName, "Whisky") || contains(categoryName, "Vodka") || contains(categoryName, "Rum"):
				breakdown.IMFL = append(breakdown.IMFL, entry)
			case contains(categoryName, "Beer"):
				breakdown.Beer = append(breakdown.Beer, entry)
			case contains(categoryName, "Wine"):
				breakdown.Wine = append(breakdown.Wine, entry)
			default:
				breakdown.IMFL = append(breakdown.IMFL, entry)
			}
		}
	}

	breakdown.CalculateTotals()
	return breakdown
}

// buildStockBreakdownFromReturns builds stock breakdown from returns
func (s *DailyReportService) buildStockBreakdownFromReturns(returns []sharedModels.SaleReturn) models.StockBreakdown {
	breakdown := models.StockBreakdown{
		CountryLiquor: []models.BottleEntry{},
		IMFL:          []models.BottleEntry{},
		Beer:          []models.BottleEntry{},
		Wine:          []models.BottleEntry{},
	}

	for _, ret := range returns {
		for _, item := range ret.Items {
			// Get product from SaleItem relation
			var saleItem sharedModels.SaleItem
			if err := s.db.Preload("Product").Preload("Product.Category").First(&saleItem, "id = ?", item.SaleItemID).Error; err != nil {
				continue
			}

			if saleItem.Product == nil {
				continue
			}

			entry := models.BottleEntry{
				ProductID:   saleItem.ProductID.String(),
				ProductName: saleItem.Product.Name,
				Quantity:    item.Quantity,
				UnitPrice:   item.UnitPrice,
				TotalValue:  item.TotalAmount,
			}

			// Use category name to determine bottle type
			categoryName := ""
			if saleItem.Product.Category != nil {
				categoryName = saleItem.Product.Category.Name
			}

			switch {
			case contains(categoryName, "Country") || contains(categoryName, "CL"):
				breakdown.CountryLiquor = append(breakdown.CountryLiquor, entry)
			case contains(categoryName, "IMFL") || contains(categoryName, "Whisky") || contains(categoryName, "Vodka") || contains(categoryName, "Rum"):
				breakdown.IMFL = append(breakdown.IMFL, entry)
			case contains(categoryName, "Beer"):
				breakdown.Beer = append(breakdown.Beer, entry)
			case contains(categoryName, "Wine"):
				breakdown.Wine = append(breakdown.Wine, entry)
			default:
				breakdown.IMFL = append(breakdown.IMFL, entry)
			}
		}
	}

	breakdown.CalculateTotals()
	return breakdown
}

// getConsiderationFeesPaid calculates total consideration fees paid today
func (s *DailyReportService) getConsiderationFeesPaid(tenantID uuid.UUID, reportDate time.Time) float64 {
	var total float64
	s.db.Model(&sharedModels.VendorTransaction{}).
		Where("tenant_id = ? AND is_consideration_fee = ? AND DATE(transaction_date) = ?",
			tenantID, true, reportDate.Format("2006-01-02")).
		Select("COALESCE(SUM(amount), 0)").
		Scan(&total)
	return total
}

// UploadToPortal uploads a report to the UP Excise portal
func (s *DailyReportService) UploadToPortal(tenantID, reportID uuid.UUID) (*models.ExciseDailyReport, error) {
	var report models.ExciseDailyReport
	if err := s.db.Where("id = ? AND tenant_id = ?", reportID, tenantID).First(&report).Error; err != nil {
		return nil, fmt.Errorf("report not found: %w", err)
	}

	if report.UploadedToPortal {
		return nil, errors.New("report already uploaded to portal")
	}

	// Upload to portal
	smsConfirmation, err := s.portalClient.UploadDailyReport(&report)
	if err != nil {
		// Increment attempt counter
		s.db.Model(&report).UpdateColumn("upload_attempts", report.UploadAttempts+1)
		s.db.Model(&report).UpdateColumn("portal_status", "failed")

		s.logComplianceEvent(tenantID, "portal_upload_failed", "error",
			fmt.Sprintf("Failed to upload report to portal: %s", err.Error()),
			map[string]interface{}{
				"report_id":   reportID,
				"attempt":     report.UploadAttempts + 1,
				"error":       err.Error(),
			})

		return nil, fmt.Errorf("failed to upload to portal: %w", err)
	}

	// Update report status
	now := time.Now()
	updates := map[string]interface{}{
		"uploaded_to_portal":     true,
		"upload_timestamp":       now,
		"sms_confirmation":       smsConfirmation,
		"upload_attempts":        report.UploadAttempts + 1,
		"portal_status":          "success",
		"report_status":          "uploaded",
	}
	if err := s.db.Model(&report).Updates(updates).Error; err != nil {
		return nil, fmt.Errorf("failed to update report status: %w", err)
	}

	// Log success
	s.logComplianceEvent(tenantID, "portal_upload_success", "info",
		"Daily report uploaded to portal successfully",
		map[string]interface{}{
			"report_id":         reportID,
			"sms_confirmation":  smsConfirmation,
			"uploaded_at":       now,
		})

	report.UploadedToPortal = true
	report.UploadTimestamp = &now
	report.SMSConfirmation = smsConfirmation

	return &report, nil
}

// GetReportByDate retrieves a report by date
func (s *DailyReportService) GetReportByDate(tenantID, shopID uuid.UUID, reportDate time.Time) (*models.DailyReportResponse, error) {
	var report models.ExciseDailyReport
	if err := s.db.Where("shop_id = ? AND tenant_id = ? AND report_date = ?", shopID, tenantID, reportDate).
		First(&report).Error; err != nil {
		return nil, fmt.Errorf("report not found: %w", err)
	}

	return s.buildReportResponse(&report)
}

// GetReportByID retrieves a report by ID
func (s *DailyReportService) GetReportByID(tenantID, reportID uuid.UUID) (*models.DailyReportResponse, error) {
	var report models.ExciseDailyReport
	if err := s.db.Where("id = ? AND tenant_id = ?", reportID, tenantID).First(&report).Error; err != nil {
		return nil, fmt.Errorf("report not found: %w", err)
	}

	return s.buildReportResponse(&report)
}

// GetPendingReports retrieves reports not yet uploaded to portal
func (s *DailyReportService) GetPendingReports(tenantID uuid.UUID, filters map[string]interface{}) ([]*models.DailyReportResponse, error) {
	query := s.db.Where("tenant_id = ? AND uploaded_to_portal = ?", tenantID, false)

	if shopID, ok := filters["shop_id"].(uuid.UUID); ok {
		query = query.Where("shop_id = ?", shopID)
	}

	var reports []models.ExciseDailyReport
	if err := query.Order("report_date DESC").Find(&reports).Error; err != nil {
		return nil, fmt.Errorf("failed to fetch pending reports: %w", err)
	}

	responses := make([]*models.DailyReportResponse, len(reports))
	for i, report := range reports {
		resp, _ := s.buildReportResponse(&report)
		responses[i] = resp
	}

	return responses, nil
}

// RetryUpload retries uploading a failed report
func (s *DailyReportService) RetryUpload(tenantID, reportID uuid.UUID) (*models.ExciseDailyReport, error) {
	return s.UploadToPortal(tenantID, reportID)
}

// buildReportResponse builds a detailed report response
func (s *DailyReportService) buildReportResponse(report *models.ExciseDailyReport) (*models.DailyReportResponse, error) {
	var shop sharedModels.Shop
	s.db.First(&shop, "id = ?", report.ShopID)

	var license models.ExciseLicense
	s.db.First(&license, "id = ?", report.LicenseID)

	response := &models.DailyReportResponse{
		ExciseDailyReport: *report,
		ShopName:          shop.Name,
		LicenseNumber:     license.LicenseNumber,
		IsValid:           report.ValidateReport(),
		ValidationErrors:  report.GetValidationErrors(),
	}

	return response, nil
}

// logComplianceEvent is a helper to log compliance events
func (s *DailyReportService) logComplianceEvent(tenantID uuid.UUID, logType, logLevel, message string, details map[string]interface{}) {
	log := models.ExciseComplianceLog{
		ID:       uuid.New(),
		TenantID: tenantID,
		LogType:  logType,
		LogLevel: logLevel,
		Message:  message,
		Details:  details,
	}
	s.db.Create(&log)
}

// contains is a helper function to check if a string contains a substring
func contains(s, substr string) bool {
	return strings.Contains(strings.ToLower(s), strings.ToLower(substr))
}
