apiVersion: apps/v1
kind: Deployment
metadata:
  name: gateway
  namespace: liquorpro
  labels:
    app: gateway
    service: gateway
spec:
  replicas: 2
  selector:
    matchLabels:
      app: gateway
  template:
    metadata:
      labels:
        app: gateway
        service: gateway
    spec:
      containers:
      - name: gateway
        image: liquorpro/gateway:latest
        ports:
        - containerPort: 8090
        env:
        - name: DATABASE_PASSWORD
          valueFrom:
            secretKeyRef:
              name: liquorpro-secrets
              key: db-password
        - name: REDIS_PASSWORD
          valueFrom:
            secretKeyRef:
              name: liquorpro-secrets
              key: redis-password
        - name: JWT_SECRET
          valueFrom:
            secretKeyRef:
              name: liquorpro-secrets
              key: jwt-secret
        envFrom:
        - configMapRef:
            name: liquorpro-config
        resources:
          requests:
            memory: "128Mi"
            cpu: "100m"
          limits:
            memory: "512Mi"
            cpu: "500m"
        livenessProbe:
          httpGet:
            path: /health
            port: 8090
          initialDelaySeconds: 30
          periodSeconds: 30
        readinessProbe:
          httpGet:
            path: /health
            port: 8090
          initialDelaySeconds: 5
          periodSeconds: 10
        securityContext:
          runAsNonRoot: true
          runAsUser: 1001
          allowPrivilegeEscalation: false

---
apiVersion: v1
kind: Service
metadata:
  name: gateway
  namespace: liquorpro
  labels:
    app: gateway
spec:
  type: ClusterIP
  ports:
  - port: 8090
    targetPort: 8090
    name: http
  selector:
    app: gateway

---
apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: gateway-hpa
  namespace: liquorpro
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: gateway
  minReplicas: 2
  maxReplicas: 10
  metrics:
  - type: Resource
    resource:
      name: cpu
      target:
        type: Utilization
        averageUtilization: 70
  - type: Resource
    resource:
      name: memory
      target:
        type: Utilization
        averageUtilization: 80