apiVersion: v1
kind: Namespace
metadata:
  name: liquorpro
  labels:
    name: liquorpro
    istio-injection: enabled
---
apiVersion: v1
kind: Namespace
metadata:
  name: liquorpro-monitoring
  labels:
    name: liquorpro-monitoring
---
apiVersion: v1
kind: Namespace
metadata:
  name: liquorpro-kafka
  labels:
    name: liquorpro-kafka