// Mocks generated by Mockito 5.4.6 from annotations
// in saas_admin_flutter_app/test/widget/brand_management_widget_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i5;
import 'dart:ui' as _i6;

import 'package:mockito/mockito.dart' as _i1;
import 'package:mockito/src/dummies.dart' as _i4;
import 'package:saas_admin_flutter_app/core/models/brand_model.dart' as _i3;
import 'package:saas_admin_flutter_app/features/brand_management/controllers/brand_provider.dart'
    as _i2;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class
// ignore_for_file: invalid_use_of_internal_member

/// A class which mocks [BrandProvider].
///
/// See the documentation for Mockito's code generation for more information.
class MockBrandProvider extends _i1.Mock implements _i2.BrandProvider {
  MockBrandProvider() {
    _i1.throwOnMissingStub(this);
  }

  @override
  List<_i3.Brand> get brands => (super.noSuchMethod(
        Invocation.getter(#brands),
        returnValue: <_i3.Brand>[],
      ) as List<_i3.Brand>);

  @override
  List<_i3.BrandCategory> get categories => (super.noSuchMethod(
        Invocation.getter(#categories),
        returnValue: <_i3.BrandCategory>[],
      ) as List<_i3.BrandCategory>);

  @override
  List<_i3.BrandSubcategory> get subcategories => (super.noSuchMethod(
        Invocation.getter(#subcategories),
        returnValue: <_i3.BrandSubcategory>[],
      ) as List<_i3.BrandSubcategory>);

  @override
  List<_i3.BrandVariant> get currentBrandVariants => (super.noSuchMethod(
        Invocation.getter(#currentBrandVariants),
        returnValue: <_i3.BrandVariant>[],
      ) as List<_i3.BrandVariant>);

  @override
  bool get isLoading => (super.noSuchMethod(
        Invocation.getter(#isLoading),
        returnValue: false,
      ) as bool);

  @override
  bool get isCreating => (super.noSuchMethod(
        Invocation.getter(#isCreating),
        returnValue: false,
      ) as bool);

  @override
  bool get isUpdating => (super.noSuchMethod(
        Invocation.getter(#isUpdating),
        returnValue: false,
      ) as bool);

  @override
  bool get isDeleting => (super.noSuchMethod(
        Invocation.getter(#isDeleting),
        returnValue: false,
      ) as bool);

  @override
  bool get isGridView => (super.noSuchMethod(
        Invocation.getter(#isGridView),
        returnValue: false,
      ) as bool);

  @override
  String get sortBy => (super.noSuchMethod(
        Invocation.getter(#sortBy),
        returnValue: _i4.dummyValue<String>(
          this,
          Invocation.getter(#sortBy),
        ),
      ) as String);

  @override
  bool get sortAscending => (super.noSuchMethod(
        Invocation.getter(#sortAscending),
        returnValue: false,
      ) as bool);

  @override
  List<_i3.Brand> get filteredBrands => (super.noSuchMethod(
        Invocation.getter(#filteredBrands),
        returnValue: <_i3.Brand>[],
      ) as List<_i3.Brand>);

  @override
  List<_i3.BrandSubcategory> get filteredSubcategories => (super.noSuchMethod(
        Invocation.getter(#filteredSubcategories),
        returnValue: <_i3.BrandSubcategory>[],
      ) as List<_i3.BrandSubcategory>);

  @override
  bool get hasListeners => (super.noSuchMethod(
        Invocation.getter(#hasListeners),
        returnValue: false,
      ) as bool);

  @override
  _i5.Future<void> loadBrands({
    bool? includeVariants = true,
    bool? showLoading = true,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #loadBrands,
          [],
          {
            #includeVariants: includeVariants,
            #showLoading: showLoading,
          },
        ),
        returnValue: _i5.Future<void>.value(),
        returnValueForMissingStub: _i5.Future<void>.value(),
      ) as _i5.Future<void>);

  @override
  _i5.Future<bool> createBrand(_i3.CreateBrandRequest? request) =>
      (super.noSuchMethod(
        Invocation.method(
          #createBrand,
          [request],
        ),
        returnValue: _i5.Future<bool>.value(false),
      ) as _i5.Future<bool>);

  @override
  _i5.Future<bool> createBrandWithVariants(
          _i3.CreateBrandWithVariantsRequest? request) =>
      (super.noSuchMethod(
        Invocation.method(
          #createBrandWithVariants,
          [request],
        ),
        returnValue: _i5.Future<bool>.value(false),
      ) as _i5.Future<bool>);

  @override
  _i5.Future<bool> updateBrand(
    String? brandId,
    _i3.CreateBrandRequest? request,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #updateBrand,
          [
            brandId,
            request,
          ],
        ),
        returnValue: _i5.Future<bool>.value(false),
      ) as _i5.Future<bool>);

  @override
  _i5.Future<bool> deleteBrand(String? brandId) => (super.noSuchMethod(
        Invocation.method(
          #deleteBrand,
          [brandId],
        ),
        returnValue: _i5.Future<bool>.value(false),
      ) as _i5.Future<bool>);

  @override
  _i5.Future<void> loadBrandVariants(String? brandId) => (super.noSuchMethod(
        Invocation.method(
          #loadBrandVariants,
          [brandId],
        ),
        returnValue: _i5.Future<void>.value(),
        returnValueForMissingStub: _i5.Future<void>.value(),
      ) as _i5.Future<void>);

  @override
  _i5.Future<bool> createBrandVariant(_i3.CreateBrandVariantRequest? request) =>
      (super.noSuchMethod(
        Invocation.method(
          #createBrandVariant,
          [request],
        ),
        returnValue: _i5.Future<bool>.value(false),
      ) as _i5.Future<bool>);

  @override
  _i5.Future<bool> updateBrandVariant(
    String? variantId,
    _i3.CreateBrandVariantRequest? request,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #updateBrandVariant,
          [
            variantId,
            request,
          ],
        ),
        returnValue: _i5.Future<bool>.value(false),
      ) as _i5.Future<bool>);

  @override
  _i5.Future<bool> deleteBrandVariant(String? variantId) => (super.noSuchMethod(
        Invocation.method(
          #deleteBrandVariant,
          [variantId],
        ),
        returnValue: _i5.Future<bool>.value(false),
      ) as _i5.Future<bool>);

  @override
  _i5.Future<void> loadBrandCategories() => (super.noSuchMethod(
        Invocation.method(
          #loadBrandCategories,
          [],
        ),
        returnValue: _i5.Future<void>.value(),
        returnValueForMissingStub: _i5.Future<void>.value(),
      ) as _i5.Future<void>);

  @override
  _i5.Future<bool> createBrandCategory(
          _i3.CreateBrandCategoryRequest? request) =>
      (super.noSuchMethod(
        Invocation.method(
          #createBrandCategory,
          [request],
        ),
        returnValue: _i5.Future<bool>.value(false),
      ) as _i5.Future<bool>);

  @override
  _i5.Future<void> loadBrandSubcategories({String? categoryId}) =>
      (super.noSuchMethod(
        Invocation.method(
          #loadBrandSubcategories,
          [],
          {#categoryId: categoryId},
        ),
        returnValue: _i5.Future<void>.value(),
        returnValueForMissingStub: _i5.Future<void>.value(),
      ) as _i5.Future<void>);

  @override
  _i5.Future<bool> createBrandSubcategory(
          _i3.CreateBrandSubcategoryRequest? request) =>
      (super.noSuchMethod(
        Invocation.method(
          #createBrandSubcategory,
          [request],
        ),
        returnValue: _i5.Future<bool>.value(false),
      ) as _i5.Future<bool>);

  @override
  _i5.Future<bool> assignBrandsToTenant(
          _i3.TenantBrandAssignmentRequest? request) =>
      (super.noSuchMethod(
        Invocation.method(
          #assignBrandsToTenant,
          [request],
        ),
        returnValue: _i5.Future<bool>.value(false),
      ) as _i5.Future<bool>);

  @override
  _i5.Future<List<_i3.Brand>> loadTenantBrands(String? tenantId) =>
      (super.noSuchMethod(
        Invocation.method(
          #loadTenantBrands,
          [tenantId],
        ),
        returnValue: _i5.Future<List<_i3.Brand>>.value(<_i3.Brand>[]),
      ) as _i5.Future<List<_i3.Brand>>);

  @override
  void selectBrand(_i3.Brand? brand) => super.noSuchMethod(
        Invocation.method(
          #selectBrand,
          [brand],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void selectCategory(String? categoryId) => super.noSuchMethod(
        Invocation.method(
          #selectCategory,
          [categoryId],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void selectTenant(String? tenantId) => super.noSuchMethod(
        Invocation.method(
          #selectTenant,
          [tenantId],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void setSearchQuery(String? query) => super.noSuchMethod(
        Invocation.method(
          #setSearchQuery,
          [query],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void clearError() => super.noSuchMethod(
        Invocation.method(
          #clearError,
          [],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void clearSelection() => super.noSuchMethod(
        Invocation.method(
          #clearSelection,
          [],
        ),
        returnValueForMissingStub: null,
      );

  @override
  _i5.Future<void> searchBrands(String? query) => (super.noSuchMethod(
        Invocation.method(
          #searchBrands,
          [query],
        ),
        returnValue: _i5.Future<void>.value(),
        returnValueForMissingStub: _i5.Future<void>.value(),
      ) as _i5.Future<void>);

  @override
  _i5.Future<void> initialize() => (super.noSuchMethod(
        Invocation.method(
          #initialize,
          [],
        ),
        returnValue: _i5.Future<void>.value(),
        returnValueForMissingStub: _i5.Future<void>.value(),
      ) as _i5.Future<void>);

  @override
  _i5.Future<void> refresh() => (super.noSuchMethod(
        Invocation.method(
          #refresh,
          [],
        ),
        returnValue: _i5.Future<void>.value(),
        returnValueForMissingStub: _i5.Future<void>.value(),
      ) as _i5.Future<void>);

  @override
  void toggleViewMode() => super.noSuchMethod(
        Invocation.method(
          #toggleViewMode,
          [],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void setSortBy(String? sortBy) => super.noSuchMethod(
        Invocation.method(
          #setSortBy,
          [sortBy],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void setSortAscending(bool? ascending) => super.noSuchMethod(
        Invocation.method(
          #setSortAscending,
          [ascending],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void applySorting() => super.noSuchMethod(
        Invocation.method(
          #applySorting,
          [],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void setStatusFilter(bool? status) => super.noSuchMethod(
        Invocation.method(
          #setStatusFilter,
          [status],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void clearFilters() => super.noSuchMethod(
        Invocation.method(
          #clearFilters,
          [],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void addListener(_i6.VoidCallback? listener) => super.noSuchMethod(
        Invocation.method(
          #addListener,
          [listener],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void removeListener(_i6.VoidCallback? listener) => super.noSuchMethod(
        Invocation.method(
          #removeListener,
          [listener],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void dispose() => super.noSuchMethod(
        Invocation.method(
          #dispose,
          [],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void notifyListeners() => super.noSuchMethod(
        Invocation.method(
          #notifyListeners,
          [],
        ),
        returnValueForMissingStub: null,
      );
}
