// Mocks generated by Mockito 5.4.6 from annotations
// in saas_admin_flutter_app/test/unit/controllers/brand_provider_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i4;

import 'package:mockito/mockito.dart' as _i1;
import 'package:saas_admin_flutter_app/core/models/api_response.dart' as _i2;
import 'package:saas_admin_flutter_app/core/models/brand_model.dart' as _i5;
import 'package:saas_admin_flutter_app/core/services/brand_service.dart' as _i3;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class
// ignore_for_file: invalid_use_of_internal_member

class _FakeApiResponse_0<T> extends _i1.SmartFake
    implements _i2.ApiResponse<T> {
  _FakeApiResponse_0(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

/// A class which mocks [BrandService].
///
/// See the documentation for Mockito's code generation for more information.
class MockBrandService extends _i1.Mock implements _i3.BrandService {
  MockBrandService() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i4.Future<_i2.ApiResponse<List<_i5.Brand>>> getAllBrands(
          {bool? includeVariants = false}) =>
      (super.noSuchMethod(
        Invocation.method(
          #getAllBrands,
          [],
          {#includeVariants: includeVariants},
        ),
        returnValue: _i4.Future<_i2.ApiResponse<List<_i5.Brand>>>.value(
            _FakeApiResponse_0<List<_i5.Brand>>(
          this,
          Invocation.method(
            #getAllBrands,
            [],
            {#includeVariants: includeVariants},
          ),
        )),
      ) as _i4.Future<_i2.ApiResponse<List<_i5.Brand>>>);

  @override
  _i4.Future<_i2.ApiResponse<_i5.Brand>> getBrandById(
    String? brandId, {
    bool? includeVariants = true,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #getBrandById,
          [brandId],
          {#includeVariants: includeVariants},
        ),
        returnValue: _i4.Future<_i2.ApiResponse<_i5.Brand>>.value(
            _FakeApiResponse_0<_i5.Brand>(
          this,
          Invocation.method(
            #getBrandById,
            [brandId],
            {#includeVariants: includeVariants},
          ),
        )),
      ) as _i4.Future<_i2.ApiResponse<_i5.Brand>>);

  @override
  _i4.Future<_i2.ApiResponse<_i5.Brand>> createBrand(
          _i5.CreateBrandRequest? request) =>
      (super.noSuchMethod(
        Invocation.method(
          #createBrand,
          [request],
        ),
        returnValue: _i4.Future<_i2.ApiResponse<_i5.Brand>>.value(
            _FakeApiResponse_0<_i5.Brand>(
          this,
          Invocation.method(
            #createBrand,
            [request],
          ),
        )),
      ) as _i4.Future<_i2.ApiResponse<_i5.Brand>>);

  @override
  _i4.Future<_i2.ApiResponse<_i5.Brand>> updateBrand(
    String? brandId,
    _i5.CreateBrandRequest? request,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #updateBrand,
          [
            brandId,
            request,
          ],
        ),
        returnValue: _i4.Future<_i2.ApiResponse<_i5.Brand>>.value(
            _FakeApiResponse_0<_i5.Brand>(
          this,
          Invocation.method(
            #updateBrand,
            [
              brandId,
              request,
            ],
          ),
        )),
      ) as _i4.Future<_i2.ApiResponse<_i5.Brand>>);

  @override
  _i4.Future<_i2.ApiResponse<void>> deleteBrand(String? brandId) =>
      (super.noSuchMethod(
        Invocation.method(
          #deleteBrand,
          [brandId],
        ),
        returnValue:
            _i4.Future<_i2.ApiResponse<void>>.value(_FakeApiResponse_0<void>(
          this,
          Invocation.method(
            #deleteBrand,
            [brandId],
          ),
        )),
      ) as _i4.Future<_i2.ApiResponse<void>>);

  @override
  _i4.Future<_i2.ApiResponse<List<_i5.BrandVariant>>> getBrandVariants(
          String? brandId) =>
      (super.noSuchMethod(
        Invocation.method(
          #getBrandVariants,
          [brandId],
        ),
        returnValue: _i4.Future<_i2.ApiResponse<List<_i5.BrandVariant>>>.value(
            _FakeApiResponse_0<List<_i5.BrandVariant>>(
          this,
          Invocation.method(
            #getBrandVariants,
            [brandId],
          ),
        )),
      ) as _i4.Future<_i2.ApiResponse<List<_i5.BrandVariant>>>);

  @override
  _i4.Future<_i2.ApiResponse<_i5.BrandVariant>> createBrandVariant(
          _i5.CreateBrandVariantRequest? request) =>
      (super.noSuchMethod(
        Invocation.method(
          #createBrandVariant,
          [request],
        ),
        returnValue: _i4.Future<_i2.ApiResponse<_i5.BrandVariant>>.value(
            _FakeApiResponse_0<_i5.BrandVariant>(
          this,
          Invocation.method(
            #createBrandVariant,
            [request],
          ),
        )),
      ) as _i4.Future<_i2.ApiResponse<_i5.BrandVariant>>);

  @override
  _i4.Future<_i2.ApiResponse<_i5.BrandVariant>> updateBrandVariant(
    String? variantId,
    _i5.CreateBrandVariantRequest? request,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #updateBrandVariant,
          [
            variantId,
            request,
          ],
        ),
        returnValue: _i4.Future<_i2.ApiResponse<_i5.BrandVariant>>.value(
            _FakeApiResponse_0<_i5.BrandVariant>(
          this,
          Invocation.method(
            #updateBrandVariant,
            [
              variantId,
              request,
            ],
          ),
        )),
      ) as _i4.Future<_i2.ApiResponse<_i5.BrandVariant>>);

  @override
  _i4.Future<_i2.ApiResponse<void>> deleteBrandVariant(String? variantId) =>
      (super.noSuchMethod(
        Invocation.method(
          #deleteBrandVariant,
          [variantId],
        ),
        returnValue:
            _i4.Future<_i2.ApiResponse<void>>.value(_FakeApiResponse_0<void>(
          this,
          Invocation.method(
            #deleteBrandVariant,
            [variantId],
          ),
        )),
      ) as _i4.Future<_i2.ApiResponse<void>>);

  @override
  _i4.Future<_i2.ApiResponse<List<_i5.BrandCategory>>> getBrandCategories() =>
      (super.noSuchMethod(
        Invocation.method(
          #getBrandCategories,
          [],
        ),
        returnValue: _i4.Future<_i2.ApiResponse<List<_i5.BrandCategory>>>.value(
            _FakeApiResponse_0<List<_i5.BrandCategory>>(
          this,
          Invocation.method(
            #getBrandCategories,
            [],
          ),
        )),
      ) as _i4.Future<_i2.ApiResponse<List<_i5.BrandCategory>>>);

  @override
  _i4.Future<_i2.ApiResponse<_i5.BrandCategory>> createBrandCategory(
          _i5.CreateBrandCategoryRequest? request) =>
      (super.noSuchMethod(
        Invocation.method(
          #createBrandCategory,
          [request],
        ),
        returnValue: _i4.Future<_i2.ApiResponse<_i5.BrandCategory>>.value(
            _FakeApiResponse_0<_i5.BrandCategory>(
          this,
          Invocation.method(
            #createBrandCategory,
            [request],
          ),
        )),
      ) as _i4.Future<_i2.ApiResponse<_i5.BrandCategory>>);

  @override
  _i4.Future<_i2.ApiResponse<List<_i5.BrandSubcategory>>> getBrandSubcategories(
          {String? categoryId}) =>
      (super.noSuchMethod(
        Invocation.method(
          #getBrandSubcategories,
          [],
          {#categoryId: categoryId},
        ),
        returnValue:
            _i4.Future<_i2.ApiResponse<List<_i5.BrandSubcategory>>>.value(
                _FakeApiResponse_0<List<_i5.BrandSubcategory>>(
          this,
          Invocation.method(
            #getBrandSubcategories,
            [],
            {#categoryId: categoryId},
          ),
        )),
      ) as _i4.Future<_i2.ApiResponse<List<_i5.BrandSubcategory>>>);

  @override
  _i4.Future<_i2.ApiResponse<_i5.BrandSubcategory>> createBrandSubcategory(
          _i5.CreateBrandSubcategoryRequest? request) =>
      (super.noSuchMethod(
        Invocation.method(
          #createBrandSubcategory,
          [request],
        ),
        returnValue: _i4.Future<_i2.ApiResponse<_i5.BrandSubcategory>>.value(
            _FakeApiResponse_0<_i5.BrandSubcategory>(
          this,
          Invocation.method(
            #createBrandSubcategory,
            [request],
          ),
        )),
      ) as _i4.Future<_i2.ApiResponse<_i5.BrandSubcategory>>);

  @override
  _i4.Future<_i2.ApiResponse<void>> assignBrandsToTenant(
          _i5.TenantBrandAssignmentRequest? request) =>
      (super.noSuchMethod(
        Invocation.method(
          #assignBrandsToTenant,
          [request],
        ),
        returnValue:
            _i4.Future<_i2.ApiResponse<void>>.value(_FakeApiResponse_0<void>(
          this,
          Invocation.method(
            #assignBrandsToTenant,
            [request],
          ),
        )),
      ) as _i4.Future<_i2.ApiResponse<void>>);

  @override
  _i4.Future<_i2.ApiResponse<List<_i5.Brand>>> getTenantBrands(
          String? tenantId) =>
      (super.noSuchMethod(
        Invocation.method(
          #getTenantBrands,
          [tenantId],
        ),
        returnValue: _i4.Future<_i2.ApiResponse<List<_i5.Brand>>>.value(
            _FakeApiResponse_0<List<_i5.Brand>>(
          this,
          Invocation.method(
            #getTenantBrands,
            [tenantId],
          ),
        )),
      ) as _i4.Future<_i2.ApiResponse<List<_i5.Brand>>>);

  @override
  _i4.Future<_i2.ApiResponse<List<_i5.Brand>>> getPublicBrands({
    bool? includeVariants = false,
    String? categoryId,
    int? page = 1,
    int? limit = 20,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #getPublicBrands,
          [],
          {
            #includeVariants: includeVariants,
            #categoryId: categoryId,
            #page: page,
            #limit: limit,
          },
        ),
        returnValue: _i4.Future<_i2.ApiResponse<List<_i5.Brand>>>.value(
            _FakeApiResponse_0<List<_i5.Brand>>(
          this,
          Invocation.method(
            #getPublicBrands,
            [],
            {
              #includeVariants: includeVariants,
              #categoryId: categoryId,
              #page: page,
              #limit: limit,
            },
          ),
        )),
      ) as _i4.Future<_i2.ApiResponse<List<_i5.Brand>>>);

  @override
  _i4.Future<_i2.ApiResponse<Map<String, dynamic>>> bulkCreateBrands(
          List<Map<String, dynamic>>? bulkRequest) =>
      (super.noSuchMethod(
        Invocation.method(
          #bulkCreateBrands,
          [bulkRequest],
        ),
        returnValue: _i4.Future<_i2.ApiResponse<Map<String, dynamic>>>.value(
            _FakeApiResponse_0<Map<String, dynamic>>(
          this,
          Invocation.method(
            #bulkCreateBrands,
            [bulkRequest],
          ),
        )),
      ) as _i4.Future<_i2.ApiResponse<Map<String, dynamic>>>);

  @override
  _i4.Future<_i2.ApiResponse<List<_i5.Brand>>> searchBrands({
    required String? query,
    bool? includeVariants = false,
    String? categoryId,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #searchBrands,
          [],
          {
            #query: query,
            #includeVariants: includeVariants,
            #categoryId: categoryId,
          },
        ),
        returnValue: _i4.Future<_i2.ApiResponse<List<_i5.Brand>>>.value(
            _FakeApiResponse_0<List<_i5.Brand>>(
          this,
          Invocation.method(
            #searchBrands,
            [],
            {
              #query: query,
              #includeVariants: includeVariants,
              #categoryId: categoryId,
            },
          ),
        )),
      ) as _i4.Future<_i2.ApiResponse<List<_i5.Brand>>>);
}
