// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        v6.33.0
// source: pkg/grpc/inventory/inventory.proto

package inventory

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// Messages
type GetProductRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	TenantId      string                 `protobuf:"bytes,2,opt,name=tenant_id,json=tenantId,proto3" json:"tenant_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetProductRequest) Reset() {
	*x = GetProductRequest{}
	mi := &file_pkg_grpc_inventory_inventory_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetProductRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetProductRequest) ProtoMessage() {}

func (x *GetProductRequest) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_grpc_inventory_inventory_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetProductRequest.ProtoReflect.Descriptor instead.
func (*GetProductRequest) Descriptor() ([]byte, []int) {
	return file_pkg_grpc_inventory_inventory_proto_rawDescGZIP(), []int{0}
}

func (x *GetProductRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *GetProductRequest) GetTenantId() string {
	if x != nil {
		return x.TenantId
	}
	return ""
}

type ListProductsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TenantId      string                 `protobuf:"bytes,1,opt,name=tenant_id,json=tenantId,proto3" json:"tenant_id,omitempty"`
	Page          int32                  `protobuf:"varint,2,opt,name=page,proto3" json:"page,omitempty"`
	PageSize      int32                  `protobuf:"varint,3,opt,name=page_size,json=pageSize,proto3" json:"page_size,omitempty"`
	CategoryId    string                 `protobuf:"bytes,4,opt,name=category_id,json=categoryId,proto3" json:"category_id,omitempty"`
	Search        string                 `protobuf:"bytes,5,opt,name=search,proto3" json:"search,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListProductsRequest) Reset() {
	*x = ListProductsRequest{}
	mi := &file_pkg_grpc_inventory_inventory_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListProductsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListProductsRequest) ProtoMessage() {}

func (x *ListProductsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_grpc_inventory_inventory_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListProductsRequest.ProtoReflect.Descriptor instead.
func (*ListProductsRequest) Descriptor() ([]byte, []int) {
	return file_pkg_grpc_inventory_inventory_proto_rawDescGZIP(), []int{1}
}

func (x *ListProductsRequest) GetTenantId() string {
	if x != nil {
		return x.TenantId
	}
	return ""
}

func (x *ListProductsRequest) GetPage() int32 {
	if x != nil {
		return x.Page
	}
	return 0
}

func (x *ListProductsRequest) GetPageSize() int32 {
	if x != nil {
		return x.PageSize
	}
	return 0
}

func (x *ListProductsRequest) GetCategoryId() string {
	if x != nil {
		return x.CategoryId
	}
	return ""
}

func (x *ListProductsRequest) GetSearch() string {
	if x != nil {
		return x.Search
	}
	return ""
}

type CreateProductRequest struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	TenantId       string                 `protobuf:"bytes,1,opt,name=tenant_id,json=tenantId,proto3" json:"tenant_id,omitempty"`
	Name           string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	CategoryId     string                 `protobuf:"bytes,3,opt,name=category_id,json=categoryId,proto3" json:"category_id,omitempty"`
	BrandId        string                 `protobuf:"bytes,4,opt,name=brand_id,json=brandId,proto3" json:"brand_id,omitempty"`
	Price          float64                `protobuf:"fixed64,5,opt,name=price,proto3" json:"price,omitempty"`
	Cost           float64                `protobuf:"fixed64,6,opt,name=cost,proto3" json:"cost,omitempty"`
	Barcode        string                 `protobuf:"bytes,7,opt,name=barcode,proto3" json:"barcode,omitempty"`
	Sku            string                 `protobuf:"bytes,8,opt,name=sku,proto3" json:"sku,omitempty"`
	Description    string                 `protobuf:"bytes,9,opt,name=description,proto3" json:"description,omitempty"`
	Size           string                 `protobuf:"bytes,10,opt,name=size,proto3" json:"size,omitempty"`
	AlcoholContent float64                `protobuf:"fixed64,11,opt,name=alcohol_content,json=alcoholContent,proto3" json:"alcohol_content,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *CreateProductRequest) Reset() {
	*x = CreateProductRequest{}
	mi := &file_pkg_grpc_inventory_inventory_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateProductRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateProductRequest) ProtoMessage() {}

func (x *CreateProductRequest) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_grpc_inventory_inventory_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateProductRequest.ProtoReflect.Descriptor instead.
func (*CreateProductRequest) Descriptor() ([]byte, []int) {
	return file_pkg_grpc_inventory_inventory_proto_rawDescGZIP(), []int{2}
}

func (x *CreateProductRequest) GetTenantId() string {
	if x != nil {
		return x.TenantId
	}
	return ""
}

func (x *CreateProductRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *CreateProductRequest) GetCategoryId() string {
	if x != nil {
		return x.CategoryId
	}
	return ""
}

func (x *CreateProductRequest) GetBrandId() string {
	if x != nil {
		return x.BrandId
	}
	return ""
}

func (x *CreateProductRequest) GetPrice() float64 {
	if x != nil {
		return x.Price
	}
	return 0
}

func (x *CreateProductRequest) GetCost() float64 {
	if x != nil {
		return x.Cost
	}
	return 0
}

func (x *CreateProductRequest) GetBarcode() string {
	if x != nil {
		return x.Barcode
	}
	return ""
}

func (x *CreateProductRequest) GetSku() string {
	if x != nil {
		return x.Sku
	}
	return ""
}

func (x *CreateProductRequest) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *CreateProductRequest) GetSize() string {
	if x != nil {
		return x.Size
	}
	return ""
}

func (x *CreateProductRequest) GetAlcoholContent() float64 {
	if x != nil {
		return x.AlcoholContent
	}
	return 0
}

type UpdateProductRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	TenantId      string                 `protobuf:"bytes,2,opt,name=tenant_id,json=tenantId,proto3" json:"tenant_id,omitempty"`
	Name          string                 `protobuf:"bytes,3,opt,name=name,proto3" json:"name,omitempty"`
	CategoryId    string                 `protobuf:"bytes,4,opt,name=category_id,json=categoryId,proto3" json:"category_id,omitempty"`
	Price         float64                `protobuf:"fixed64,5,opt,name=price,proto3" json:"price,omitempty"`
	Cost          float64                `protobuf:"fixed64,6,opt,name=cost,proto3" json:"cost,omitempty"`
	Description   string                 `protobuf:"bytes,7,opt,name=description,proto3" json:"description,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateProductRequest) Reset() {
	*x = UpdateProductRequest{}
	mi := &file_pkg_grpc_inventory_inventory_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateProductRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateProductRequest) ProtoMessage() {}

func (x *UpdateProductRequest) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_grpc_inventory_inventory_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateProductRequest.ProtoReflect.Descriptor instead.
func (*UpdateProductRequest) Descriptor() ([]byte, []int) {
	return file_pkg_grpc_inventory_inventory_proto_rawDescGZIP(), []int{3}
}

func (x *UpdateProductRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *UpdateProductRequest) GetTenantId() string {
	if x != nil {
		return x.TenantId
	}
	return ""
}

func (x *UpdateProductRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *UpdateProductRequest) GetCategoryId() string {
	if x != nil {
		return x.CategoryId
	}
	return ""
}

func (x *UpdateProductRequest) GetPrice() float64 {
	if x != nil {
		return x.Price
	}
	return 0
}

func (x *UpdateProductRequest) GetCost() float64 {
	if x != nil {
		return x.Cost
	}
	return 0
}

func (x *UpdateProductRequest) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

type DeleteProductRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	TenantId      string                 `protobuf:"bytes,2,opt,name=tenant_id,json=tenantId,proto3" json:"tenant_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteProductRequest) Reset() {
	*x = DeleteProductRequest{}
	mi := &file_pkg_grpc_inventory_inventory_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteProductRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteProductRequest) ProtoMessage() {}

func (x *DeleteProductRequest) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_grpc_inventory_inventory_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteProductRequest.ProtoReflect.Descriptor instead.
func (*DeleteProductRequest) Descriptor() ([]byte, []int) {
	return file_pkg_grpc_inventory_inventory_proto_rawDescGZIP(), []int{4}
}

func (x *DeleteProductRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *DeleteProductRequest) GetTenantId() string {
	if x != nil {
		return x.TenantId
	}
	return ""
}

type ProductResponse struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	Id             string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	TenantId       string                 `protobuf:"bytes,2,opt,name=tenant_id,json=tenantId,proto3" json:"tenant_id,omitempty"`
	Name           string                 `protobuf:"bytes,3,opt,name=name,proto3" json:"name,omitempty"`
	CategoryId     string                 `protobuf:"bytes,4,opt,name=category_id,json=categoryId,proto3" json:"category_id,omitempty"`
	BrandId        string                 `protobuf:"bytes,5,opt,name=brand_id,json=brandId,proto3" json:"brand_id,omitempty"`
	Price          float64                `protobuf:"fixed64,6,opt,name=price,proto3" json:"price,omitempty"`
	Cost           float64                `protobuf:"fixed64,7,opt,name=cost,proto3" json:"cost,omitempty"`
	Barcode        string                 `protobuf:"bytes,8,opt,name=barcode,proto3" json:"barcode,omitempty"`
	Sku            string                 `protobuf:"bytes,9,opt,name=sku,proto3" json:"sku,omitempty"`
	Description    string                 `protobuf:"bytes,10,opt,name=description,proto3" json:"description,omitempty"`
	Size           string                 `protobuf:"bytes,11,opt,name=size,proto3" json:"size,omitempty"`
	AlcoholContent float64                `protobuf:"fixed64,12,opt,name=alcohol_content,json=alcoholContent,proto3" json:"alcohol_content,omitempty"`
	Mrp            float64                `protobuf:"fixed64,13,opt,name=mrp,proto3" json:"mrp,omitempty"`
	CreatedAt      string                 `protobuf:"bytes,14,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	UpdatedAt      string                 `protobuf:"bytes,15,opt,name=updated_at,json=updatedAt,proto3" json:"updated_at,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *ProductResponse) Reset() {
	*x = ProductResponse{}
	mi := &file_pkg_grpc_inventory_inventory_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ProductResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ProductResponse) ProtoMessage() {}

func (x *ProductResponse) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_grpc_inventory_inventory_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ProductResponse.ProtoReflect.Descriptor instead.
func (*ProductResponse) Descriptor() ([]byte, []int) {
	return file_pkg_grpc_inventory_inventory_proto_rawDescGZIP(), []int{5}
}

func (x *ProductResponse) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *ProductResponse) GetTenantId() string {
	if x != nil {
		return x.TenantId
	}
	return ""
}

func (x *ProductResponse) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *ProductResponse) GetCategoryId() string {
	if x != nil {
		return x.CategoryId
	}
	return ""
}

func (x *ProductResponse) GetBrandId() string {
	if x != nil {
		return x.BrandId
	}
	return ""
}

func (x *ProductResponse) GetPrice() float64 {
	if x != nil {
		return x.Price
	}
	return 0
}

func (x *ProductResponse) GetCost() float64 {
	if x != nil {
		return x.Cost
	}
	return 0
}

func (x *ProductResponse) GetBarcode() string {
	if x != nil {
		return x.Barcode
	}
	return ""
}

func (x *ProductResponse) GetSku() string {
	if x != nil {
		return x.Sku
	}
	return ""
}

func (x *ProductResponse) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *ProductResponse) GetSize() string {
	if x != nil {
		return x.Size
	}
	return ""
}

func (x *ProductResponse) GetAlcoholContent() float64 {
	if x != nil {
		return x.AlcoholContent
	}
	return 0
}

func (x *ProductResponse) GetMrp() float64 {
	if x != nil {
		return x.Mrp
	}
	return 0
}

func (x *ProductResponse) GetCreatedAt() string {
	if x != nil {
		return x.CreatedAt
	}
	return ""
}

func (x *ProductResponse) GetUpdatedAt() string {
	if x != nil {
		return x.UpdatedAt
	}
	return ""
}

type ListProductsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Products      []*ProductResponse     `protobuf:"bytes,1,rep,name=products,proto3" json:"products,omitempty"`
	Total         int32                  `protobuf:"varint,2,opt,name=total,proto3" json:"total,omitempty"`
	Page          int32                  `protobuf:"varint,3,opt,name=page,proto3" json:"page,omitempty"`
	PageSize      int32                  `protobuf:"varint,4,opt,name=page_size,json=pageSize,proto3" json:"page_size,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListProductsResponse) Reset() {
	*x = ListProductsResponse{}
	mi := &file_pkg_grpc_inventory_inventory_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListProductsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListProductsResponse) ProtoMessage() {}

func (x *ListProductsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_grpc_inventory_inventory_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListProductsResponse.ProtoReflect.Descriptor instead.
func (*ListProductsResponse) Descriptor() ([]byte, []int) {
	return file_pkg_grpc_inventory_inventory_proto_rawDescGZIP(), []int{6}
}

func (x *ListProductsResponse) GetProducts() []*ProductResponse {
	if x != nil {
		return x.Products
	}
	return nil
}

func (x *ListProductsResponse) GetTotal() int32 {
	if x != nil {
		return x.Total
	}
	return 0
}

func (x *ListProductsResponse) GetPage() int32 {
	if x != nil {
		return x.Page
	}
	return 0
}

func (x *ListProductsResponse) GetPageSize() int32 {
	if x != nil {
		return x.PageSize
	}
	return 0
}

type GetStockRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ProductId     string                 `protobuf:"bytes,1,opt,name=product_id,json=productId,proto3" json:"product_id,omitempty"`
	ShopId        string                 `protobuf:"bytes,2,opt,name=shop_id,json=shopId,proto3" json:"shop_id,omitempty"`
	TenantId      string                 `protobuf:"bytes,3,opt,name=tenant_id,json=tenantId,proto3" json:"tenant_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetStockRequest) Reset() {
	*x = GetStockRequest{}
	mi := &file_pkg_grpc_inventory_inventory_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetStockRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetStockRequest) ProtoMessage() {}

func (x *GetStockRequest) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_grpc_inventory_inventory_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetStockRequest.ProtoReflect.Descriptor instead.
func (*GetStockRequest) Descriptor() ([]byte, []int) {
	return file_pkg_grpc_inventory_inventory_proto_rawDescGZIP(), []int{7}
}

func (x *GetStockRequest) GetProductId() string {
	if x != nil {
		return x.ProductId
	}
	return ""
}

func (x *GetStockRequest) GetShopId() string {
	if x != nil {
		return x.ShopId
	}
	return ""
}

func (x *GetStockRequest) GetTenantId() string {
	if x != nil {
		return x.TenantId
	}
	return ""
}

type AdjustStockRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ProductId     string                 `protobuf:"bytes,1,opt,name=product_id,json=productId,proto3" json:"product_id,omitempty"`
	ShopId        string                 `protobuf:"bytes,2,opt,name=shop_id,json=shopId,proto3" json:"shop_id,omitempty"`
	TenantId      string                 `protobuf:"bytes,3,opt,name=tenant_id,json=tenantId,proto3" json:"tenant_id,omitempty"`
	Quantity      int32                  `protobuf:"varint,4,opt,name=quantity,proto3" json:"quantity,omitempty"`
	Reason        string                 `protobuf:"bytes,5,opt,name=reason,proto3" json:"reason,omitempty"`
	AdjustedBy    string                 `protobuf:"bytes,6,opt,name=adjusted_by,json=adjustedBy,proto3" json:"adjusted_by,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AdjustStockRequest) Reset() {
	*x = AdjustStockRequest{}
	mi := &file_pkg_grpc_inventory_inventory_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AdjustStockRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AdjustStockRequest) ProtoMessage() {}

func (x *AdjustStockRequest) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_grpc_inventory_inventory_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AdjustStockRequest.ProtoReflect.Descriptor instead.
func (*AdjustStockRequest) Descriptor() ([]byte, []int) {
	return file_pkg_grpc_inventory_inventory_proto_rawDescGZIP(), []int{8}
}

func (x *AdjustStockRequest) GetProductId() string {
	if x != nil {
		return x.ProductId
	}
	return ""
}

func (x *AdjustStockRequest) GetShopId() string {
	if x != nil {
		return x.ShopId
	}
	return ""
}

func (x *AdjustStockRequest) GetTenantId() string {
	if x != nil {
		return x.TenantId
	}
	return ""
}

func (x *AdjustStockRequest) GetQuantity() int32 {
	if x != nil {
		return x.Quantity
	}
	return 0
}

func (x *AdjustStockRequest) GetReason() string {
	if x != nil {
		return x.Reason
	}
	return ""
}

func (x *AdjustStockRequest) GetAdjustedBy() string {
	if x != nil {
		return x.AdjustedBy
	}
	return ""
}

type StockResponse struct {
	state             protoimpl.MessageState `protogen:"open.v1"`
	ProductId         string                 `protobuf:"bytes,1,opt,name=product_id,json=productId,proto3" json:"product_id,omitempty"`
	ShopId            string                 `protobuf:"bytes,2,opt,name=shop_id,json=shopId,proto3" json:"shop_id,omitempty"`
	Quantity          int32                  `protobuf:"varint,3,opt,name=quantity,proto3" json:"quantity,omitempty"`
	ReservedQuantity  int32                  `protobuf:"varint,4,opt,name=reserved_quantity,json=reservedQuantity,proto3" json:"reserved_quantity,omitempty"`
	AvailableQuantity int32                  `protobuf:"varint,5,opt,name=available_quantity,json=availableQuantity,proto3" json:"available_quantity,omitempty"`
	LastUpdated       string                 `protobuf:"bytes,6,opt,name=last_updated,json=lastUpdated,proto3" json:"last_updated,omitempty"`
	unknownFields     protoimpl.UnknownFields
	sizeCache         protoimpl.SizeCache
}

func (x *StockResponse) Reset() {
	*x = StockResponse{}
	mi := &file_pkg_grpc_inventory_inventory_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StockResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StockResponse) ProtoMessage() {}

func (x *StockResponse) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_grpc_inventory_inventory_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StockResponse.ProtoReflect.Descriptor instead.
func (*StockResponse) Descriptor() ([]byte, []int) {
	return file_pkg_grpc_inventory_inventory_proto_rawDescGZIP(), []int{9}
}

func (x *StockResponse) GetProductId() string {
	if x != nil {
		return x.ProductId
	}
	return ""
}

func (x *StockResponse) GetShopId() string {
	if x != nil {
		return x.ShopId
	}
	return ""
}

func (x *StockResponse) GetQuantity() int32 {
	if x != nil {
		return x.Quantity
	}
	return 0
}

func (x *StockResponse) GetReservedQuantity() int32 {
	if x != nil {
		return x.ReservedQuantity
	}
	return 0
}

func (x *StockResponse) GetAvailableQuantity() int32 {
	if x != nil {
		return x.AvailableQuantity
	}
	return 0
}

func (x *StockResponse) GetLastUpdated() string {
	if x != nil {
		return x.LastUpdated
	}
	return ""
}

type BulkStockUpdateRequest struct {
	state         protoimpl.MessageState                `protogen:"open.v1"`
	TenantId      string                                `protobuf:"bytes,1,opt,name=tenant_id,json=tenantId,proto3" json:"tenant_id,omitempty"`
	ShopId        string                                `protobuf:"bytes,2,opt,name=shop_id,json=shopId,proto3" json:"shop_id,omitempty"`
	Updates       []*BulkStockUpdateRequest_StockUpdate `protobuf:"bytes,3,rep,name=updates,proto3" json:"updates,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *BulkStockUpdateRequest) Reset() {
	*x = BulkStockUpdateRequest{}
	mi := &file_pkg_grpc_inventory_inventory_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BulkStockUpdateRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BulkStockUpdateRequest) ProtoMessage() {}

func (x *BulkStockUpdateRequest) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_grpc_inventory_inventory_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BulkStockUpdateRequest.ProtoReflect.Descriptor instead.
func (*BulkStockUpdateRequest) Descriptor() ([]byte, []int) {
	return file_pkg_grpc_inventory_inventory_proto_rawDescGZIP(), []int{10}
}

func (x *BulkStockUpdateRequest) GetTenantId() string {
	if x != nil {
		return x.TenantId
	}
	return ""
}

func (x *BulkStockUpdateRequest) GetShopId() string {
	if x != nil {
		return x.ShopId
	}
	return ""
}

func (x *BulkStockUpdateRequest) GetUpdates() []*BulkStockUpdateRequest_StockUpdate {
	if x != nil {
		return x.Updates
	}
	return nil
}

type BulkStockUpdateResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UpdatedCount  int32                  `protobuf:"varint,1,opt,name=updated_count,json=updatedCount,proto3" json:"updated_count,omitempty"`
	FailedCount   int32                  `protobuf:"varint,2,opt,name=failed_count,json=failedCount,proto3" json:"failed_count,omitempty"`
	Errors        []string               `protobuf:"bytes,3,rep,name=errors,proto3" json:"errors,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *BulkStockUpdateResponse) Reset() {
	*x = BulkStockUpdateResponse{}
	mi := &file_pkg_grpc_inventory_inventory_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BulkStockUpdateResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BulkStockUpdateResponse) ProtoMessage() {}

func (x *BulkStockUpdateResponse) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_grpc_inventory_inventory_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BulkStockUpdateResponse.ProtoReflect.Descriptor instead.
func (*BulkStockUpdateResponse) Descriptor() ([]byte, []int) {
	return file_pkg_grpc_inventory_inventory_proto_rawDescGZIP(), []int{11}
}

func (x *BulkStockUpdateResponse) GetUpdatedCount() int32 {
	if x != nil {
		return x.UpdatedCount
	}
	return 0
}

func (x *BulkStockUpdateResponse) GetFailedCount() int32 {
	if x != nil {
		return x.FailedCount
	}
	return 0
}

func (x *BulkStockUpdateResponse) GetErrors() []string {
	if x != nil {
		return x.Errors
	}
	return nil
}

type DeleteResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteResponse) Reset() {
	*x = DeleteResponse{}
	mi := &file_pkg_grpc_inventory_inventory_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteResponse) ProtoMessage() {}

func (x *DeleteResponse) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_grpc_inventory_inventory_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteResponse.ProtoReflect.Descriptor instead.
func (*DeleteResponse) Descriptor() ([]byte, []int) {
	return file_pkg_grpc_inventory_inventory_proto_rawDescGZIP(), []int{12}
}

func (x *DeleteResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *DeleteResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

type StreamStockRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TenantId      string                 `protobuf:"bytes,1,opt,name=tenant_id,json=tenantId,proto3" json:"tenant_id,omitempty"`
	ShopId        string                 `protobuf:"bytes,2,opt,name=shop_id,json=shopId,proto3" json:"shop_id,omitempty"`
	ProductIds    []string               `protobuf:"bytes,3,rep,name=product_ids,json=productIds,proto3" json:"product_ids,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StreamStockRequest) Reset() {
	*x = StreamStockRequest{}
	mi := &file_pkg_grpc_inventory_inventory_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StreamStockRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StreamStockRequest) ProtoMessage() {}

func (x *StreamStockRequest) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_grpc_inventory_inventory_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StreamStockRequest.ProtoReflect.Descriptor instead.
func (*StreamStockRequest) Descriptor() ([]byte, []int) {
	return file_pkg_grpc_inventory_inventory_proto_rawDescGZIP(), []int{13}
}

func (x *StreamStockRequest) GetTenantId() string {
	if x != nil {
		return x.TenantId
	}
	return ""
}

func (x *StreamStockRequest) GetShopId() string {
	if x != nil {
		return x.ShopId
	}
	return ""
}

func (x *StreamStockRequest) GetProductIds() []string {
	if x != nil {
		return x.ProductIds
	}
	return nil
}

type StockUpdateEvent struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ProductId     string                 `protobuf:"bytes,1,opt,name=product_id,json=productId,proto3" json:"product_id,omitempty"`
	ShopId        string                 `protobuf:"bytes,2,opt,name=shop_id,json=shopId,proto3" json:"shop_id,omitempty"`
	OldQuantity   int32                  `protobuf:"varint,3,opt,name=old_quantity,json=oldQuantity,proto3" json:"old_quantity,omitempty"`
	NewQuantity   int32                  `protobuf:"varint,4,opt,name=new_quantity,json=newQuantity,proto3" json:"new_quantity,omitempty"`
	Reason        string                 `protobuf:"bytes,5,opt,name=reason,proto3" json:"reason,omitempty"`
	Timestamp     string                 `protobuf:"bytes,6,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StockUpdateEvent) Reset() {
	*x = StockUpdateEvent{}
	mi := &file_pkg_grpc_inventory_inventory_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StockUpdateEvent) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StockUpdateEvent) ProtoMessage() {}

func (x *StockUpdateEvent) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_grpc_inventory_inventory_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StockUpdateEvent.ProtoReflect.Descriptor instead.
func (*StockUpdateEvent) Descriptor() ([]byte, []int) {
	return file_pkg_grpc_inventory_inventory_proto_rawDescGZIP(), []int{14}
}

func (x *StockUpdateEvent) GetProductId() string {
	if x != nil {
		return x.ProductId
	}
	return ""
}

func (x *StockUpdateEvent) GetShopId() string {
	if x != nil {
		return x.ShopId
	}
	return ""
}

func (x *StockUpdateEvent) GetOldQuantity() int32 {
	if x != nil {
		return x.OldQuantity
	}
	return 0
}

func (x *StockUpdateEvent) GetNewQuantity() int32 {
	if x != nil {
		return x.NewQuantity
	}
	return 0
}

func (x *StockUpdateEvent) GetReason() string {
	if x != nil {
		return x.Reason
	}
	return ""
}

func (x *StockUpdateEvent) GetTimestamp() string {
	if x != nil {
		return x.Timestamp
	}
	return ""
}

type StreamProductRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TenantId      string                 `protobuf:"bytes,1,opt,name=tenant_id,json=tenantId,proto3" json:"tenant_id,omitempty"`
	ShopId        string                 `protobuf:"bytes,2,opt,name=shop_id,json=shopId,proto3" json:"shop_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StreamProductRequest) Reset() {
	*x = StreamProductRequest{}
	mi := &file_pkg_grpc_inventory_inventory_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StreamProductRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StreamProductRequest) ProtoMessage() {}

func (x *StreamProductRequest) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_grpc_inventory_inventory_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StreamProductRequest.ProtoReflect.Descriptor instead.
func (*StreamProductRequest) Descriptor() ([]byte, []int) {
	return file_pkg_grpc_inventory_inventory_proto_rawDescGZIP(), []int{15}
}

func (x *StreamProductRequest) GetTenantId() string {
	if x != nil {
		return x.TenantId
	}
	return ""
}

func (x *StreamProductRequest) GetShopId() string {
	if x != nil {
		return x.ShopId
	}
	return ""
}

type ProductChangeEvent struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	EventType     string                 `protobuf:"bytes,1,opt,name=event_type,json=eventType,proto3" json:"event_type,omitempty"` // "created", "updated", "deleted"
	Product       *ProductResponse       `protobuf:"bytes,2,opt,name=product,proto3" json:"product,omitempty"`
	Timestamp     string                 `protobuf:"bytes,3,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ProductChangeEvent) Reset() {
	*x = ProductChangeEvent{}
	mi := &file_pkg_grpc_inventory_inventory_proto_msgTypes[16]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ProductChangeEvent) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ProductChangeEvent) ProtoMessage() {}

func (x *ProductChangeEvent) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_grpc_inventory_inventory_proto_msgTypes[16]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ProductChangeEvent.ProtoReflect.Descriptor instead.
func (*ProductChangeEvent) Descriptor() ([]byte, []int) {
	return file_pkg_grpc_inventory_inventory_proto_rawDescGZIP(), []int{16}
}

func (x *ProductChangeEvent) GetEventType() string {
	if x != nil {
		return x.EventType
	}
	return ""
}

func (x *ProductChangeEvent) GetProduct() *ProductResponse {
	if x != nil {
		return x.Product
	}
	return nil
}

func (x *ProductChangeEvent) GetTimestamp() string {
	if x != nil {
		return x.Timestamp
	}
	return ""
}

type BulkStockUpdateRequest_StockUpdate struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ProductId     string                 `protobuf:"bytes,1,opt,name=product_id,json=productId,proto3" json:"product_id,omitempty"`
	Quantity      int32                  `protobuf:"varint,2,opt,name=quantity,proto3" json:"quantity,omitempty"`
	Reason        string                 `protobuf:"bytes,3,opt,name=reason,proto3" json:"reason,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *BulkStockUpdateRequest_StockUpdate) Reset() {
	*x = BulkStockUpdateRequest_StockUpdate{}
	mi := &file_pkg_grpc_inventory_inventory_proto_msgTypes[17]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BulkStockUpdateRequest_StockUpdate) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BulkStockUpdateRequest_StockUpdate) ProtoMessage() {}

func (x *BulkStockUpdateRequest_StockUpdate) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_grpc_inventory_inventory_proto_msgTypes[17]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BulkStockUpdateRequest_StockUpdate.ProtoReflect.Descriptor instead.
func (*BulkStockUpdateRequest_StockUpdate) Descriptor() ([]byte, []int) {
	return file_pkg_grpc_inventory_inventory_proto_rawDescGZIP(), []int{10, 0}
}

func (x *BulkStockUpdateRequest_StockUpdate) GetProductId() string {
	if x != nil {
		return x.ProductId
	}
	return ""
}

func (x *BulkStockUpdateRequest_StockUpdate) GetQuantity() int32 {
	if x != nil {
		return x.Quantity
	}
	return 0
}

func (x *BulkStockUpdateRequest_StockUpdate) GetReason() string {
	if x != nil {
		return x.Reason
	}
	return ""
}

var File_pkg_grpc_inventory_inventory_proto protoreflect.FileDescriptor

const file_pkg_grpc_inventory_inventory_proto_rawDesc = "" +
	"\n" +
	"\"pkg/grpc/inventory/inventory.proto\x12\tinventory\"@\n" +
	"\x11GetProductRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x1b\n" +
	"\ttenant_id\x18\x02 \x01(\tR\btenantId\"\x9c\x01\n" +
	"\x13ListProductsRequest\x12\x1b\n" +
	"\ttenant_id\x18\x01 \x01(\tR\btenantId\x12\x12\n" +
	"\x04page\x18\x02 \x01(\x05R\x04page\x12\x1b\n" +
	"\tpage_size\x18\x03 \x01(\x05R\bpageSize\x12\x1f\n" +
	"\vcategory_id\x18\x04 \x01(\tR\n" +
	"categoryId\x12\x16\n" +
	"\x06search\x18\x05 \x01(\tR\x06search\"\xb8\x02\n" +
	"\x14CreateProductRequest\x12\x1b\n" +
	"\ttenant_id\x18\x01 \x01(\tR\btenantId\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12\x1f\n" +
	"\vcategory_id\x18\x03 \x01(\tR\n" +
	"categoryId\x12\x19\n" +
	"\bbrand_id\x18\x04 \x01(\tR\abrandId\x12\x14\n" +
	"\x05price\x18\x05 \x01(\x01R\x05price\x12\x12\n" +
	"\x04cost\x18\x06 \x01(\x01R\x04cost\x12\x18\n" +
	"\abarcode\x18\a \x01(\tR\abarcode\x12\x10\n" +
	"\x03sku\x18\b \x01(\tR\x03sku\x12 \n" +
	"\vdescription\x18\t \x01(\tR\vdescription\x12\x12\n" +
	"\x04size\x18\n" +
	" \x01(\tR\x04size\x12'\n" +
	"\x0falcohol_content\x18\v \x01(\x01R\x0ealcoholContent\"\xc4\x01\n" +
	"\x14UpdateProductRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x1b\n" +
	"\ttenant_id\x18\x02 \x01(\tR\btenantId\x12\x12\n" +
	"\x04name\x18\x03 \x01(\tR\x04name\x12\x1f\n" +
	"\vcategory_id\x18\x04 \x01(\tR\n" +
	"categoryId\x12\x14\n" +
	"\x05price\x18\x05 \x01(\x01R\x05price\x12\x12\n" +
	"\x04cost\x18\x06 \x01(\x01R\x04cost\x12 \n" +
	"\vdescription\x18\a \x01(\tR\vdescription\"C\n" +
	"\x14DeleteProductRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x1b\n" +
	"\ttenant_id\x18\x02 \x01(\tR\btenantId\"\x93\x03\n" +
	"\x0fProductResponse\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x1b\n" +
	"\ttenant_id\x18\x02 \x01(\tR\btenantId\x12\x12\n" +
	"\x04name\x18\x03 \x01(\tR\x04name\x12\x1f\n" +
	"\vcategory_id\x18\x04 \x01(\tR\n" +
	"categoryId\x12\x19\n" +
	"\bbrand_id\x18\x05 \x01(\tR\abrandId\x12\x14\n" +
	"\x05price\x18\x06 \x01(\x01R\x05price\x12\x12\n" +
	"\x04cost\x18\a \x01(\x01R\x04cost\x12\x18\n" +
	"\abarcode\x18\b \x01(\tR\abarcode\x12\x10\n" +
	"\x03sku\x18\t \x01(\tR\x03sku\x12 \n" +
	"\vdescription\x18\n" +
	" \x01(\tR\vdescription\x12\x12\n" +
	"\x04size\x18\v \x01(\tR\x04size\x12'\n" +
	"\x0falcohol_content\x18\f \x01(\x01R\x0ealcoholContent\x12\x10\n" +
	"\x03mrp\x18\r \x01(\x01R\x03mrp\x12\x1d\n" +
	"\n" +
	"created_at\x18\x0e \x01(\tR\tcreatedAt\x12\x1d\n" +
	"\n" +
	"updated_at\x18\x0f \x01(\tR\tupdatedAt\"\x95\x01\n" +
	"\x14ListProductsResponse\x126\n" +
	"\bproducts\x18\x01 \x03(\v2\x1a.inventory.ProductResponseR\bproducts\x12\x14\n" +
	"\x05total\x18\x02 \x01(\x05R\x05total\x12\x12\n" +
	"\x04page\x18\x03 \x01(\x05R\x04page\x12\x1b\n" +
	"\tpage_size\x18\x04 \x01(\x05R\bpageSize\"f\n" +
	"\x0fGetStockRequest\x12\x1d\n" +
	"\n" +
	"product_id\x18\x01 \x01(\tR\tproductId\x12\x17\n" +
	"\ashop_id\x18\x02 \x01(\tR\x06shopId\x12\x1b\n" +
	"\ttenant_id\x18\x03 \x01(\tR\btenantId\"\xbe\x01\n" +
	"\x12AdjustStockRequest\x12\x1d\n" +
	"\n" +
	"product_id\x18\x01 \x01(\tR\tproductId\x12\x17\n" +
	"\ashop_id\x18\x02 \x01(\tR\x06shopId\x12\x1b\n" +
	"\ttenant_id\x18\x03 \x01(\tR\btenantId\x12\x1a\n" +
	"\bquantity\x18\x04 \x01(\x05R\bquantity\x12\x16\n" +
	"\x06reason\x18\x05 \x01(\tR\x06reason\x12\x1f\n" +
	"\vadjusted_by\x18\x06 \x01(\tR\n" +
	"adjustedBy\"\xe2\x01\n" +
	"\rStockResponse\x12\x1d\n" +
	"\n" +
	"product_id\x18\x01 \x01(\tR\tproductId\x12\x17\n" +
	"\ashop_id\x18\x02 \x01(\tR\x06shopId\x12\x1a\n" +
	"\bquantity\x18\x03 \x01(\x05R\bquantity\x12+\n" +
	"\x11reserved_quantity\x18\x04 \x01(\x05R\x10reservedQuantity\x12-\n" +
	"\x12available_quantity\x18\x05 \x01(\x05R\x11availableQuantity\x12!\n" +
	"\flast_updated\x18\x06 \x01(\tR\vlastUpdated\"\xf9\x01\n" +
	"\x16BulkStockUpdateRequest\x12\x1b\n" +
	"\ttenant_id\x18\x01 \x01(\tR\btenantId\x12\x17\n" +
	"\ashop_id\x18\x02 \x01(\tR\x06shopId\x12G\n" +
	"\aupdates\x18\x03 \x03(\v2-.inventory.BulkStockUpdateRequest.StockUpdateR\aupdates\x1a`\n" +
	"\vStockUpdate\x12\x1d\n" +
	"\n" +
	"product_id\x18\x01 \x01(\tR\tproductId\x12\x1a\n" +
	"\bquantity\x18\x02 \x01(\x05R\bquantity\x12\x16\n" +
	"\x06reason\x18\x03 \x01(\tR\x06reason\"y\n" +
	"\x17BulkStockUpdateResponse\x12#\n" +
	"\rupdated_count\x18\x01 \x01(\x05R\fupdatedCount\x12!\n" +
	"\ffailed_count\x18\x02 \x01(\x05R\vfailedCount\x12\x16\n" +
	"\x06errors\x18\x03 \x03(\tR\x06errors\"D\n" +
	"\x0eDeleteResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\"k\n" +
	"\x12StreamStockRequest\x12\x1b\n" +
	"\ttenant_id\x18\x01 \x01(\tR\btenantId\x12\x17\n" +
	"\ashop_id\x18\x02 \x01(\tR\x06shopId\x12\x1f\n" +
	"\vproduct_ids\x18\x03 \x03(\tR\n" +
	"productIds\"\xc6\x01\n" +
	"\x10StockUpdateEvent\x12\x1d\n" +
	"\n" +
	"product_id\x18\x01 \x01(\tR\tproductId\x12\x17\n" +
	"\ashop_id\x18\x02 \x01(\tR\x06shopId\x12!\n" +
	"\fold_quantity\x18\x03 \x01(\x05R\voldQuantity\x12!\n" +
	"\fnew_quantity\x18\x04 \x01(\x05R\vnewQuantity\x12\x16\n" +
	"\x06reason\x18\x05 \x01(\tR\x06reason\x12\x1c\n" +
	"\ttimestamp\x18\x06 \x01(\tR\ttimestamp\"L\n" +
	"\x14StreamProductRequest\x12\x1b\n" +
	"\ttenant_id\x18\x01 \x01(\tR\btenantId\x12\x17\n" +
	"\ashop_id\x18\x02 \x01(\tR\x06shopId\"\x87\x01\n" +
	"\x12ProductChangeEvent\x12\x1d\n" +
	"\n" +
	"event_type\x18\x01 \x01(\tR\teventType\x124\n" +
	"\aproduct\x18\x02 \x01(\v2\x1a.inventory.ProductResponseR\aproduct\x12\x1c\n" +
	"\ttimestamp\x18\x03 \x01(\tR\ttimestamp2\xa6\x06\n" +
	"\x10InventoryService\x12F\n" +
	"\n" +
	"GetProduct\x12\x1c.inventory.GetProductRequest\x1a\x1a.inventory.ProductResponse\x12O\n" +
	"\fListProducts\x12\x1e.inventory.ListProductsRequest\x1a\x1f.inventory.ListProductsResponse\x12L\n" +
	"\rCreateProduct\x12\x1f.inventory.CreateProductRequest\x1a\x1a.inventory.ProductResponse\x12L\n" +
	"\rUpdateProduct\x12\x1f.inventory.UpdateProductRequest\x1a\x1a.inventory.ProductResponse\x12K\n" +
	"\rDeleteProduct\x12\x1f.inventory.DeleteProductRequest\x1a\x19.inventory.DeleteResponse\x12@\n" +
	"\bGetStock\x12\x1a.inventory.GetStockRequest\x1a\x18.inventory.StockResponse\x12F\n" +
	"\vAdjustStock\x12\x1d.inventory.AdjustStockRequest\x1a\x18.inventory.StockResponse\x12X\n" +
	"\x0fBulkStockUpdate\x12!.inventory.BulkStockUpdateRequest\x1a\".inventory.BulkStockUpdateResponse\x12R\n" +
	"\x12StreamStockUpdates\x12\x1d.inventory.StreamStockRequest\x1a\x1b.inventory.StockUpdateEvent0\x01\x12X\n" +
	"\x14StreamProductChanges\x12\x1f.inventory.StreamProductRequest\x1a\x1d.inventory.ProductChangeEvent0\x01B>Z<github.com/liquorpro/go-backend/pkg/grpc/inventory;inventoryb\x06proto3"

var (
	file_pkg_grpc_inventory_inventory_proto_rawDescOnce sync.Once
	file_pkg_grpc_inventory_inventory_proto_rawDescData []byte
)

func file_pkg_grpc_inventory_inventory_proto_rawDescGZIP() []byte {
	file_pkg_grpc_inventory_inventory_proto_rawDescOnce.Do(func() {
		file_pkg_grpc_inventory_inventory_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_pkg_grpc_inventory_inventory_proto_rawDesc), len(file_pkg_grpc_inventory_inventory_proto_rawDesc)))
	})
	return file_pkg_grpc_inventory_inventory_proto_rawDescData
}

var file_pkg_grpc_inventory_inventory_proto_msgTypes = make([]protoimpl.MessageInfo, 18)
var file_pkg_grpc_inventory_inventory_proto_goTypes = []any{
	(*GetProductRequest)(nil),                  // 0: inventory.GetProductRequest
	(*ListProductsRequest)(nil),                // 1: inventory.ListProductsRequest
	(*CreateProductRequest)(nil),               // 2: inventory.CreateProductRequest
	(*UpdateProductRequest)(nil),               // 3: inventory.UpdateProductRequest
	(*DeleteProductRequest)(nil),               // 4: inventory.DeleteProductRequest
	(*ProductResponse)(nil),                    // 5: inventory.ProductResponse
	(*ListProductsResponse)(nil),               // 6: inventory.ListProductsResponse
	(*GetStockRequest)(nil),                    // 7: inventory.GetStockRequest
	(*AdjustStockRequest)(nil),                 // 8: inventory.AdjustStockRequest
	(*StockResponse)(nil),                      // 9: inventory.StockResponse
	(*BulkStockUpdateRequest)(nil),             // 10: inventory.BulkStockUpdateRequest
	(*BulkStockUpdateResponse)(nil),            // 11: inventory.BulkStockUpdateResponse
	(*DeleteResponse)(nil),                     // 12: inventory.DeleteResponse
	(*StreamStockRequest)(nil),                 // 13: inventory.StreamStockRequest
	(*StockUpdateEvent)(nil),                   // 14: inventory.StockUpdateEvent
	(*StreamProductRequest)(nil),               // 15: inventory.StreamProductRequest
	(*ProductChangeEvent)(nil),                 // 16: inventory.ProductChangeEvent
	(*BulkStockUpdateRequest_StockUpdate)(nil), // 17: inventory.BulkStockUpdateRequest.StockUpdate
}
var file_pkg_grpc_inventory_inventory_proto_depIdxs = []int32{
	5,  // 0: inventory.ListProductsResponse.products:type_name -> inventory.ProductResponse
	17, // 1: inventory.BulkStockUpdateRequest.updates:type_name -> inventory.BulkStockUpdateRequest.StockUpdate
	5,  // 2: inventory.ProductChangeEvent.product:type_name -> inventory.ProductResponse
	0,  // 3: inventory.InventoryService.GetProduct:input_type -> inventory.GetProductRequest
	1,  // 4: inventory.InventoryService.ListProducts:input_type -> inventory.ListProductsRequest
	2,  // 5: inventory.InventoryService.CreateProduct:input_type -> inventory.CreateProductRequest
	3,  // 6: inventory.InventoryService.UpdateProduct:input_type -> inventory.UpdateProductRequest
	4,  // 7: inventory.InventoryService.DeleteProduct:input_type -> inventory.DeleteProductRequest
	7,  // 8: inventory.InventoryService.GetStock:input_type -> inventory.GetStockRequest
	8,  // 9: inventory.InventoryService.AdjustStock:input_type -> inventory.AdjustStockRequest
	10, // 10: inventory.InventoryService.BulkStockUpdate:input_type -> inventory.BulkStockUpdateRequest
	13, // 11: inventory.InventoryService.StreamStockUpdates:input_type -> inventory.StreamStockRequest
	15, // 12: inventory.InventoryService.StreamProductChanges:input_type -> inventory.StreamProductRequest
	5,  // 13: inventory.InventoryService.GetProduct:output_type -> inventory.ProductResponse
	6,  // 14: inventory.InventoryService.ListProducts:output_type -> inventory.ListProductsResponse
	5,  // 15: inventory.InventoryService.CreateProduct:output_type -> inventory.ProductResponse
	5,  // 16: inventory.InventoryService.UpdateProduct:output_type -> inventory.ProductResponse
	12, // 17: inventory.InventoryService.DeleteProduct:output_type -> inventory.DeleteResponse
	9,  // 18: inventory.InventoryService.GetStock:output_type -> inventory.StockResponse
	9,  // 19: inventory.InventoryService.AdjustStock:output_type -> inventory.StockResponse
	11, // 20: inventory.InventoryService.BulkStockUpdate:output_type -> inventory.BulkStockUpdateResponse
	14, // 21: inventory.InventoryService.StreamStockUpdates:output_type -> inventory.StockUpdateEvent
	16, // 22: inventory.InventoryService.StreamProductChanges:output_type -> inventory.ProductChangeEvent
	13, // [13:23] is the sub-list for method output_type
	3,  // [3:13] is the sub-list for method input_type
	3,  // [3:3] is the sub-list for extension type_name
	3,  // [3:3] is the sub-list for extension extendee
	0,  // [0:3] is the sub-list for field type_name
}

func init() { file_pkg_grpc_inventory_inventory_proto_init() }
func file_pkg_grpc_inventory_inventory_proto_init() {
	if File_pkg_grpc_inventory_inventory_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_pkg_grpc_inventory_inventory_proto_rawDesc), len(file_pkg_grpc_inventory_inventory_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   18,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_pkg_grpc_inventory_inventory_proto_goTypes,
		DependencyIndexes: file_pkg_grpc_inventory_inventory_proto_depIdxs,
		MessageInfos:      file_pkg_grpc_inventory_inventory_proto_msgTypes,
	}.Build()
	File_pkg_grpc_inventory_inventory_proto = out.File
	file_pkg_grpc_inventory_inventory_proto_goTypes = nil
	file_pkg_grpc_inventory_inventory_proto_depIdxs = nil
}
